### ISSUE TITLE
Group tests by language on Travis-CI

### ISSUE THREAD

**Issue by methane** [TechEmpower/FrameworkBenchmarks#1029]
After #995 , tests using same language can re-use many things.
(Language toolchain, download cache for libraries, etc...)

Grouping tests by language may make CI very faster.

**Comment by hamiltont** [comment]
FYI to all - travis-ci has asked us to implement gh#1029 because we occasionally generate quite a load on their system. It’s my intention to do this once R10 is done, and frankly I think it will reduce the frequency of seeing unexpected travis problems (tricky-to-debug network failure issues, mainly) if we’re not creating thousands of jobs across 10s of queues

**Comment by hamiltont** [comment]
Ok, so I fully implemented this in #1446 . However, you cannot put all frameworks for a language into one travis job because of the 50 minute limit. I split it as much as necessary, but the end result is terrible (many mixed logs, hard to know where a framework is, hard to maintain). 

Travis-CI contacted us and offered to increase our limits to better support maintaining the existing system with one job per framework, so for now this idea is shelved. To avoid the massive re-compilations, my current idea is to start using #1479 , which I have implemented [here](https://github.com/hamiltont/FrameworkBenchmarks/commit/153200f25da1900aba6b8ff9a4dd8028d0d510cc) and appears to be workin ok for fixing the mono installation (which now completes in ~5 minutes)
