### ISSUE TITLE
Framework tests can negatively impact other tests in the same framework

### ISSUE THREAD

**Issue by hamiltont** [TechEmpower/FrameworkBenchmarks#1228]
For example, the plaintext test runs at large concurrency and often causes servers to either completely a) hang or b) begin massively underperforming (but still responding to small checks, like curling the URLs). This causes big problems for other test types json,single,multiple,fortune, etc if plaintext is run first - all of the following tests either don't complete or have bad numbers. 

This is a nasty issue because it's subtle to notice (no big errors), has major performance implications, and impacts TFB's ability to add future test types. Given that many of our tests intentionally push servers to failure, this is definitely a problem we want to solve categorically. 

Only *hard* solution I see is to isolate tests from each other, such as turning our current pattern of this:

    start_server --> db--> json --> plaintext --> fortune --> etc --> stop_server

into 
  
    start_server --> db --> stop_server --> start_server --> json --> stop_server --> etc

This allows us to use things like `Benchmarker#__forciblyEndPortBoundProcesses` to ensure the server is totally reset between each test. However, this would drastically increase the testing time

**Comment by hamiltont** [comment]
Thought about this some more. 

FYI the precise problem is [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L444) - we run test after test against a framework without restarting the framework in between. 

I'd expect that changing the order of the tests could result in substantial differences for some underperforming frameworks. This is obviously an issue with those frameworks - if a framework starts to underperform after experiencing a period of heavy load, that's a huge problem. 

We could help frameworks avoid this challenge by restarting the framework in between each test time, although this would increase our total benchmark running time from 1 day to 6 days. 

Conclusion: This isn't TFB's battle, and if a framework starts to fail after experiencing load that is something that should be reflected in the results. I vote to close this issue as wontfix. Thoughts?

**Comment by msmith-techempower** [comment]
Ugh... this again.

There are two prevailing schools of thought on the issue I mentioned above (`plaintext` can reliably get otherwise reasonable frameworks to completely hang in amazing ways):

1. Nuke everything between test iterations (there are essentially 5 `plaintext`s run, 5 `db`s, etc at different concurrencies) and reissue another small priming run before each iteration.
2. It's at the fault of the framework/stack author, and they should resolve it.

There are MANY problems with the first, but they almost entirely boil down to "more work for TE et al" whereas the problems with the second are many and unfair. For instance, many of the Python frameworks which suffer from this problem do not seem to be stuck in actual framework code, but rather somewhere in the netstack in a Python library. While this does show a limitation of choosing such a framework, it's ultimately something in the stack outside the control of the author... and I feel like punishing the framework for a shortcoming of the language is rather punitive.

That said, it is somewhat infeasible for us to run rounds if they they take 6 days to complete. We cannot justify the cost of running Amazon EC2 instances for that long on this type of project (currently, we spin them up for the first preview and the final run, then immediately shut them down once we've captured their logs).

Sigh.

Let's remember this issue exists for future discussions on the matter, but I'm inclined to agree with @hamiltont; let's close it as wontfix for now.
