### ISSUE TITLE
Additional test types

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#133]
We plan to add new test types over time.  The following is a summary of tests we have presently and those we plan to specify and implement in the future.
1. _Present:_ JSON Serialization, in which a trivial newly-instantiated object is serialized to JSON.
2. _Present:_ Single database query, in which a single random row is fetched (via the framework's ORM) from a simple database table containing 10,000 rows and then serialized to JSON.
3. _Present:_ Multiple database queries, which is similar to the previous test but allowing the number of random rows to be specified as a URL parameter with the results rendered as a JSON list.
4. _Present:_ Server-side template and collections test.  This involves retrieving a small number of rows from the database, sorting within the application code (not within the database), and rendering to HTML via server-side templates.  No external assets will be referenced by the templates. This is detailed in issue #134.
5. _Present:_ Database update test.  This is a variation of test 2.  A single row will be fetched via the ORM, some trivial math will be applied to the random number field of the row, and then the object will be persisted using the ORM.  This is intended to exercise the ORM's ability to persist rows, so the trivial math isn't applied directly to the row using SQL.  This is detailed in issue #263.
6. _Present:_ Small plaintext responses.  This is detailed in issue #290.
7. _Future:_ Caching test.  Testing caching might begin with a variation of test 2 using the framework's caching capability, but we will also want to test caching results of more complex query operations.  See #374.  This is likely to be the next test type.
8. _Future:_ Server-side templates with assets.  This will extend test 4 and add to-be-determined assets, at least composed of a style-sheet (CSS), but possibly also including JavaScript.  Performance-wise, this likely won't differ much from test 4.  However, it will be an opportunity for readers to dig into the code and observe the frameworks' variety of approaches for handling assets.
9. _Future:_ Compression tests.  Add gzip or deflate compression to one or more test.
10. _Future:_ SSL tests.  Add SSL to one or more tests.  This is detailed in issue #3290.
11. _Future:_ WebSocket enabled tests.  (High concurrency is desirable here.)
12. _Future:_ Tests that exercise requests made to external services and therefore must go idle until the external service provides a response.  (High concurrency is desirable here.)
13. _Future:_ JSON responses with larger workloads (complex data structure serialization).
14. _Future:_ Transactional update test.  See #326.
15. _Future:_ Large plaintext responses.
16. _Future:_ Complex routing map test.  Require a given number of routes to be present to exercise the overhead of a larger routing map/table/tree.
17. _Future:_ Heavy model test, involving a larger number of entity objects and classes, as suggested by @methane in comments below.
18. _Future:_ CSRF protection and form processing test as suggested by @michaelhixson below. Note that @wg of Wrk fame has made a special version that selects from a list of requests and might allow us to run this test with Wrk.
19. _Future:_ Large static response test as suggested by @weltermann17 below.
20. _Future:_ Static file serving, to exercise the performance of the web-server.  To be clear, this test would be expected to bypass the _framework_ where applicable and be served directly by the web server or application server, whichever is available and best suited.
21. _Future:_ Penetration test(s).  This would require additional client-side testing tools (beyond the load generator we use today), but would validate the security of the platform and framework combination.
22. _Future:_ TCP-heavy test.  This test would mirror the Plaintext test but eliminate both pipelining *and* keep-alive—each request would need to be connected via a TCP socket and disconnected.  It may be the case that such a test runs into networking-layer limits in the Linux TCP stack, so we'll need to be prepared to do some tuning there.
24. _Future:_ HTTP/2 pipelined tests.  This would likely be a variant of one of the present-day simple tests (JSON Serialization or Plaintext or both), since the presumed intent of such a test would be to measure the overhead impact/benefit of switching from HTTP v1 to v2.
25. _Future:_ File upload. See #4829.

For the time being, we're still interested in relatively simple tests that exercise various components of the frameworks.  But we're also interested in hearing your thoughts on more tests for the long term.  If you have any ideas, please post them here.

**Comment by edsiper** [comment]
request: when performing plaintext test, do it in two modes: with pipelined requests and without pipelined requests. This will help to measure the internal architecture when switching between requests and processing outgoing data.

**Comment by circlespainter** [comment]
I'm with @bhauer and @hrj on the parameterized "sleep" test: it could be an easy way to test the specific strenghts of async frameworks as well as [Quasar](http://docs.paralleluniverse.co/quasar/) / [Pulsar](http://docs.paralleluniverse.co/pulsar/) / [Comsat](http://docs.paralleluniverse.co/comsat/) ones using fibers (see #1719 and #1720), which offer greater benefits when there are more outstanding requests than OS threads a box can handle.

**Comment by Drawaes** [comment]
On SSL/TLS considering their importance and prevalence these days, has a test or test pack been devised yet for this?

**Comment by Drawaes** [comment]
Is anyone looking at SSL/TLS I am happy to help as much as I can, but I think with most companies really starting to push this, it is a very important test for now and more so into the future.

**Comment by bhauer** [comment]
I have added a "TCP heavy" test type number 22 in the list above.  This is based on feedback from Daniel Nicoletti here: https://groups.google.com/d/msg/framework-benchmarks/2LRga8pkm6E/YOqNI58lAgAJ

**Comment by weltermann17** [comment]
Hi Brian,

I have trouble with my Google account therefore a mail reply. I have
noticed that our framework "plain (Scala)" has vanished from all
benchmarks. Even though it was directly mentioned e. g. in the blog for
round 8 (and can be seen in the zoomed screenshot). Is there any reason for
that? Maybe because of it's unfortunate name? We are using it quite heavily
for a number of customers, but I need to update (and maybe rename) the
published version.

Thanks in advance.

Mit freundlichen Grüßen / Kind regards

Guido Schmidt
Senior Managing Consultant
Senior Solution Architect


IBMBusiness Analytics & Strategy / Interactive Experience & Mobile DACH
                                                                                                 
                                                                                                 
                                                                                                 
                                                                                                 
                                                                                                 
                   Phone:  +49-7034-2873-123              IBM Deutschland                        
                                                                                                 
                   Mobile: +49-151-15146740               Hollerithstrasse 1                     
                                                                                                 
                   MailTo: g-schmidt@de.ibm.com           81829 München                          
                                                                                                 
                                                          Germany                                
                                                                                                 
                                                                                                 
                                                                                                 
                                                                                                 
                                                                                                 
 IBM Deutschland                                                                                 
 Global Business                                                                                 
 Solutions GmbH /                                                                                
 Geschäftsführung:                                                                               
 Michael Mai,                                                                                    
 Rainer Viering                                                                                  
 Sitz der                                                                                        
 Gesellschaft:                                                                                   
 Ehningen /                                                                                      
 Registergericht:                                                                                
 Amtsgericht                                                                                     
 Stuttgart, HRB                                                                                  
 726121                                                                                          
                                                                                                 






From:	Brian Hauer <notifications@github.com>
To:	TechEmpower/FrameworkBenchmarks
            <FrameworkBenchmarks@noreply.github.com>
Cc:	Guido Schmidt17/Germany/IBM@IBMDE, Mention
            <mention@noreply.github.com>
Date:	28.11.2016 20:04
Subject:	Re: [TechEmpower/FrameworkBenchmarks] Additional test types
            (#133)



I have added a "TCP heavy" test type number 22 in the list above. This is
based on feedback from Daniel Nicoletti here:
https://groups.google.com/d/msg/framework-benchmarks/2LRga8pkm6E/YOqNI58lAgAJ


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cjnething** [comment]
Hi @weltermann17 it looks like Scala (plain) was removed in [this PR](https://github.com/TechEmpower/FrameworkBenchmarks/pull/2275) because it wasn't working and no one could find documentation or evidence of maintenance. Pinging @knewmanTE for further help/next steps.

**Comment by knewmanTE** [comment]
@weltermann17 in an effort to clean up the suite, we removed Scala/plain because it was failing our suite's tests and appeared to be unmaintained. I apologize if this wasn't the case! If you are able to get the Scala/plain tests working again, please open up a pull request to get it back in! You can find the code for our last known implementation [here](https://github.com/TechEmpower/FrameworkBenchmarks/tree/beb9b3e9f32747cf60429e95fbebbcb8b9d7b7b8/frameworks/Scala/plain), and you can check it out with that commit (beb9b3e9f32747cf60429e95fbebbcb8b9d7b7b8). Though, to get it merged back into the main code base, you should be testing the framework on a branch that also contains the latest changes from master.

**Comment by weltermann17** [comment]
Hi Julia. Thanks for letting me know. Maybe I will add the current version. It's a pity though that the old results depend on your current config and are not stable. Regards. 

Am 29.11.2016 um 18:23 schrieb Julia Nething <notifications@github.com>:

Hi @weltermann17 it looks like Scala (plain) was removed in this PR because it wasn't working and no one could find documentation or evidence of maintenance. Pinging @knewmanTE for further help/next steps.

**Comment by greenlaw110** [comment]
I've added another proposal: [benchmark how fast frameworks handle an invalid request which should trigger a 404 response](https://github.com/TechEmpower/FrameworkBenchmarks/issues/2524)

**Comment by tmds** [comment]
> Future: SSL tests. Add SSL to one or more tests.

+1
> Future: WebSocket enabled tests. (High concurrency is desirable here.)

+1

**Comment by msmith-techempower** [comment]
Ugh... this issue has been open for so long.

We should break out each into its own issue for more simple management and clarity.

**Comment by boazsegev** [comment]
Why is SSL/TLS a framework concern? Isn't it a server/proxy concern?

In most production environments the server (nginx/apache) deals with the TLS/SSL (along with load balancing) and the framework deals with the data.

Pushing TLS/SSL into frameworks often involves reduced security and redundant code (doubling the server's job in the framework's codebase, but usually with less resources/knowledge).

Do we really want to impress upon developers TLS/SSL as a high value in the framework layer (vs. the server layer)?

**Comment by greenlaw110** [comment]
@boazsegev Agreed. Most of the frameworks **SHOULD NOT** take SSL/TLS into their consideration at all. It might support SSL/TLS to help testing, however in the real production environmenht it's the frontend server taking those jobs

**Comment by Drawaes** [comment]
So the only encryption you do is on the front end servers? "In production" many environments have TLS between layers and in service to service calls. Infact some industries (especially heavily regulated ones" require secure communication between these layers. To only secure "front end servers" and perimeter security is becoming a legacy way of thinking.

As someone who deals with and has looked into how these frameworks interact with openssl/boring/s2n/schannel there is a vast difference in performance. 

Also http/2 basically forces connections to be TLS

**Comment by benaadams** [comment]
>  Agreed. Most of the frameworks SHOULD NOT take SSL/TLS into their consideration at all.

That fine. Don't submit a test case for a TLS benchmark for that framework. Or submit an additional variant just for https which is framework+frontend server variant (+ ngnix, etc)

It still should be measured as its a very important consideration for the webstack since [50% of web traffic now runs over TLS](https://techcrunch.com/2017/02/22/eff-half-the-web-is-now-encrypted/) and by [2019 its estimated it will be 75%](https://www.nsslabs.com/company/news/press-releases/nss-labs-predicts-75-of-web-traffic-will-be-encrypted-by-2019/).

It seems non-sensible to not measure what it soon to be 75% of real world deployment scenarios for public web traffic.

**Comment by benaadams** [comment]
If a layer of ngnix; HAProxy; Apache; Squid; etc for TLS termination commonly performs badly, it should also encourage the frontend server to improve its performance; if it performs badly in isolation it will encourage the framework to look improving their integrations; if its not measured that's a huge gap in understanding missing.

**Comment by greenlaw110** [comment]
> In production" many environments have TLS between layers and in service to service calls. Infact some industries (especially heavily regulated ones" require secure communication between these layers

Can't these services service requests from other service through the frontend servers? My understanding (I might wrong) is app server always sit behind nignx (or apache httpd etc) and have it to deal with SSL/TLS and service static resources, which are not the strength of app server (normally).

> If a layer of ngnix; HAProxy; Apache; Squid; etc for TLS termination commonly performs badly.

really? my thought is these frontend servers should do good job on these low level tasks.

> if it performs badly in isolation it will encourage the framework to look improving their integrations

What kind of intergration? shouldn't that be simply a reverse proxy setup? How to improve the integration for that?

**Comment by Drawaes** [comment]
You want to route every service to service call through a front end server? And how do you secure the communication to said server?

So you have two options, a framework is usable as is or it has to be behind a proxy. If it's the later then there will also be a cost. This is the modern security reality so why wouldn't you measure it?

**Comment by benaadams** [comment]
> > If a layer of ngnix; HAProxy; Apache; Squid; etc for TLS termination commonly performs badly.

> really? my thought is these frontend servers should do good job on these low level tasks.

Not saying they don't; but if you are using framework X and it needs a frontend server which one should you pair it with? Where are the benchmarks for it? Some frameworks already act as hardened edge servers and don't need a frontend server; does that make a difference?

>  shouldn't that be simply a reverse proxy setup? How to improve the integration for that?

What's the best reverse proxy setup to use for frontend server Y and framework X, what do they support: localhost vs named pipes vs unix sockets vs shared memory etc. 

Here people are likely to hone choices down and use the best performing options; other people that do deployment will then look to the example implementations to improve their deployments when using that framework.

**Comment by greenlaw110** [comment]
@benaadams 

> What's the best reverse proxy setup to use for frontend server Y and framework X, what do they support: localhost vs named pipes vs unix sockets vs shared memory etc.

hmm... I don't know there are so many options honestly. Thanks for sharing the information.

@Drawaes 

I am actually happy to see the data. My concern is most (maybe I am wrong) framework might choose the proxy way to handle SSL/TLS, in which case framework itself doesn't have too much room to improve if there is an issue. @benaadams mentioned a few options about integration, it would be pretty interesting to see how they works, but are they really framework specific? Or they are generic practices across frameworks.

**Comment by benaadams** [comment]
> but are they really framework specific? Or they are generic practices across frameworks.

They may not be implemented, or the code path might a neglected one, or carry unnecessary overhead in a particular framework etc; don't know haven't seen benchmarks 😄 

Why I'd most like to see TLS is because the *encryption* itself on a pre-negotiated connection is *really fast* on modern CPUs; however the integration of the crypto library; whether OpenSSL, boring SSL, libsodium; Libressl; etc (**do not roll your own crypto**); can be pretty crufty. Can be too many allocations, too much copying, too granular, not granular enough, all sorts of things.

The TechEmpower benchmarks have done wonders for the performance of frameworks http performance by having a set of standardized measurements independently done; and I'd like to see that effect replicated for http**s**; whichever framework you are into. Its good for the web ecosystem as a whole.

**Comment by RX14** [comment]
I agree that HTTPS between microservices, or between the load balancer and web frontend is a good idea in general. Benchmarking this would bring visibility to the performance overhead of frameworks in this area (an aim of the test would be to be directly comparable to a http test so the https overhead could be measured for each framework).

**Comment by boazsegev** [comment]
> In production" many environments have TLS between layers and in service to service calls. Infact some industries (especially heavily regulated ones" require secure communication between these layers...

I think is [Redis a great use case example](https://redis.io/topics/encryption). Communication is performed securely using a secure tunnel (such as using [Spiped](http://www.tarsnap.com/spiped.html), [Ghostunnel](https://github.com/square/ghostunnel), etc'.

The separation of concerns between security and services is important. It allows security patches to be easily implemented across the board without patching each framework / service separately. Also, the security implementation is often superior to a BYO solution.

> What's the best reverse proxy setup to use for frontend server Y and framework X, what do they support: localhost vs named pipes vs unix sockets vs shared memory etc.

**I would love have benchmarks about TLS/SSL, but I'm not sure the benchmarks should include any frameworks**. Once we use a framework's internal TLS/SSL in a benchmark, we're telling developers that this is a production grade setup.

I'm not even sure I want to know [how many applications in the wild use security implementations with known vulnerabilities](https://www.ssllabs.com/ssltest/)... it a source for worry for me on SO whenever someone asks about implementing TLS/SSL in a backend application server.

Than again, I'll probably [implement TLS/SSL and let security be damned](https://devcentral.f5.com/articles/beware-using-internal-encryption-as-an-it-security-blanket) - the pressure to add TLS/SSL is too great and (re)explaining why security concerns should be separated from the framework is getting tiring.

**Comment by Drawaes** [comment]
Right an article on a site dedicated to edge services (F5) ... Also most of your "edge" services will use the exact same underlying lib. Eg ngnix using openssl. And if we take openssl it's often part of the os. 

So the big issue is ... How did they implement it? Did they do a lot of copying and allocations? Are there added bottle necks?

As someone who works in a very secure environment we are required to have a high security edge layer (no one said I was ditching that and we actually have many layers there) but we are also required to have ssl/TLS "Inside" that security ring. To assume a security layer and you are done in banking, health, government, education is dangerous and in some cases illegal

**Comment by boazsegev** [comment]
> Also most of your "edge" services will use the exact same underlying lib. Eg ngnix using openssl. And if we take openssl it's often part of the os.

And... if memory serves, openssl uses insecure defaults... but maybe that changed.

> As someone who works in a very secure environment...

In your experience, do you use a framework's SSL/TLS implementation for production (to secure internal network communication), or do you tunnel the communication through secure channeling (i.e., `spiped`)?

I agree that if secure production environments rely on the framework's SSL/TLS layer, than it's important to both test and benchmark that option.

**Comment by hiyelbaz** [comment]
websockets +1

**Comment by bhauer** [comment]
Commenters above who've thoughts about TLS/SSL tests please see and weigh in on the stand-alone issue (#3290).

**Comment by tmds** [comment]
Many microservices are running in 'tiny' containers. It would be interesting to see how the stacks behave in such an environment. For example: allocated 1 CPU and 500MB RAM.

**Comment by tmds** [comment]
For some time I've been running some of the TechEmpower benchmarks and trying to make sense of the results. One thought that keeps coming back is that these benchmarks are stressing the frameworks at 100% cpu. That should not be the normal operating mode of a server. I'd be interested to see latency vs throughput numbers. [wrk2](https://github.com/giltene/wrk2) can be used for such benchmarks.

**Comment by bhauer** [comment]
Added a future HTTP/2 test type based on the following comment: https://github.com/TechEmpower/FrameworkBenchmarks/issues/2978#issuecomment-485954538

**Comment by abnud1** [comment]
HTTP2  +1
