### ISSUE TITLE
Fix installed check for system-wide tool installs

### ISSUE THREAD

**Issue by marko-asplund** [TechEmpower/FrameworkBenchmarks#1385]
some tools e.g. maven are installed system-wide, but the installed check uses a file located in $IROOT, which results in extraneous errors e.g.
* when running setup with two different user accounts on the same machine or
* running setup multiple times and clearing install directory in-between

```
...
++++ wd=/home/travis/build/marko-asplund/FrameworkBenchmarks/installs
++++ relative_wd='$FWROOT/installs'
+++++ echo /toolset/setup/linux/systools/maven.sh
++++ echo 'ERROR: /toolset/setup/linux/systools/maven.sh: Command '\''sudo apt-get -y install maven'\'' exited with status 100 (dependency=maven) (cwd=$FWROOT/installs)'
ERROR: /toolset/setup/linux/systools/maven.sh: Command 'sudo apt-get -y install maven' exited with status 100 (dependency=maven) (cwd=$FWROOT/installs)
+++ mvn -version
...
```
this occurs especially on the CI server and applies at least to java (install check missing entirely) and java8, in addition to maven.

for details see: https://travis-ci.org/marko-asplund/FrameworkBenchmarks/jobs/53495677

**Comment by hamiltont** [comment]
FYI the end-goal here is to totally abandon system-wide installs for non-essential software, and place everything we can inside IROOT, such that deleting IROOT means you have a "fresh" machine. It also means that we don't have to worry about what software is already on the machines when TFB runs, because installing our own local version avoids nasty things like dependency conflicts (and as a bonus, takes us one step closer to support for multiple linux flavors). At the moment this is in a state of transition - some of the software installer files are still doing system-wide, and some of them have been transitioned to using local installations inside IROOT. 

We cannot control the start state of the Travis-CI machines unfortunately, so we've seen a ton of issues where a software install file is trying to do a system-wide installation and running into problems because travis already has that software installed system wide. The correct fix, from the point of view of this project, is to replace [this line](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/systools/maven.sh#L6) with something that does a local installation inside IROOT.

**Comment by hamiltont** [comment]
PS - I do see your point btw - [this line](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/systools/maven.sh#L3) checks inside IROOT while the install is system wide, and I do agree that this shouldn't be, just wanted to provide some context on the broader situation

**Comment by marko-asplund** [comment]
I think that makes a lot of sense and should help with making builds more reproducible esp. the CI ones.

Do any GH issues exist for this refactoring work?

**Comment by hamiltont** [comment]
No, that's a good point. Opened #1387 and tagged it as R11

**Comment by msmith-techempower** [comment]
I believe this is resolved now.
