### ISSUE TITLE
Load generator is not producing enough load

### ISSUE THREAD

**Issue by denkab** [TechEmpower/FrameworkBenchmarks#1432]
Analyzing results of test for Spring, I realized that, possibly, the load generator's concurrency is insufficient to utilize all available CPU on the hosts being tested. Number of client "threads" should be inversely proportionate to latency a framework is able to deliver, not a fixed value. Apologies if this is an invalid assumption on my part.

**Comment by msmith-techempower** [comment]
I'm going to ping @bhauer on this since I don't really know enough to comment.

**Comment by bhauer** [comment]
For the json, database query, updates, and fortunes tests, we run at concurrency levels ranging from 8 to 256.  For the plaintext test, the concurrency levels go as high as 16,384.

For threaded servers, the load generator's concurrency level is very closely tied to the maximum number of server worker threads you should expect to see utilized if you were to visualize a snapshot at any moment in time during the test.  In practice, it's quite feasible you'll see fewer actually doing work as the particular moment in time may be in between requests that the load generator is creating within its concurrency buckets.  For example, at 256 concurrency, it seems plausible that a snapshot may show, for example, 220 threads at work on the server.

From a point of view, how those requests are generated by the client is immaterial as long as the tests are not limited by the performance of the client.  With a fast-enough single core, the client could be a single threaded event loop processing all of its concurrent requests.  In practice, however, we use Wrk, which is a threaded and evented load generator.  I believe we use a number of threads equal to the CPU cores of the load generator (in the Peak environment, that's 40 HT cores).

Data from Round 11 shows that Wrk can generate at least 2.2 million non-pipelined requests per second and 6.8 million pipelined requests per second in the Peak environment.  This is (we believe) the practical limit of the 10 gigabit Ethernet.  In other words, we do not presently believe we are operating at the performance limits of the load generator.

In fact, spot testing with a *local* instance of Wrk (that is, testing that does not involve the physical network) yields even higher RPS numbers with ultra high-performance servers, even accounting for the CPU contention caused by generating load on the same CPU cores.

I'm happy to discuss this further if there is evidence that Wrk or our configuration of Wrk isn't generating sufficient load, but I do not presently think that's the case.
