### ISSUE TITLE
NO RESULTS (Did framework launch?) - Remove Results Directory Reminder

### ISSUE THREAD

**Issue by LadyMozzarella** [TechEmpower/FrameworkBenchmarks#1448]
When we're verifying tests, haven't removed the results directory (or forgot to), and "NO RESULTS (Did framework launch?)" is printed on the screen - let's add a message suggesting that it could be that the user didn't remove the previous results directory.

**Comment by hamiltont** [comment]
Or perhaps we always run, even if we find that framework in the latest run? That skipping behavior was originally added because running a round required restarting the scripts multiple times (as frameworks were not terminating properly or otherwise interfering with each other). When running the script many times to get one set of results for a round, it made sense to skip tests if they were in the latest result set. Now that meganuke works and you can reliably run the script a single time, it makes sense to do exactly what the user asked for instead of unexpectedly skipping

**Comment by msmith-techempower** [comment]
I would still prefer to warn the user that the exact test they are trying to run exist in the results directory, rather than append or overwrite the output there.

I think something as simple as "[frameworkname] exists in the results directory; this must be removed before running a new test" would suffice. The problem is that presently no useful information is given to the user to get them moving along.

**Comment by muraray** [comment]
How do I remove the exists directory "jester" 
Am stuck here https://github.com/TechEmpower/FrameworkBenchmarks/pull/5578

returned this 
```
================================================================================
Verification Summary
--------------------------------------------------------------------------------
| jester
|      NO RESULTS (Did framework launch?)
================================================================================
```

ref: http://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/670204461
Any help is appreciated
