### ISSUE TITLE
Header verification throwing unnecessary warnings and exceptions

### ISSUE THREAD

**Issue by zane-techempower** [TechEmpower/FrameworkBenchmarks#1534]
https://github.com/TechEmpower/FrameworkBenchmarks/blob/fcd51040a1ddf06046d69ed16c39c90c825e533d/toolset/benchmark/test_types/query_type.py#L105-L107

Some frameworks use a `Content-Type: application/json; charset=utf-8` header, combining the charset and content type. This will throw a warn as it doesn't match `Content-type: application/json` exactly.

**Comment by msmith-techempower** [comment]
This is a correct warning - we want to enforce equal footing for all tests, and if TestX is sending `Content-Type: application/json; charset=utf-8` instead of `Content-Type: application/json`, then they are sending extra bytes, which will affect their throughput negatively.

This is a warning because some frameworks might not be able to control this, but it should be noted that this **CAN** affect the results.

**Comment by hamiltont** [comment]
@msmith-techempower I'd vote to restate the warning though - instead of the current "Missing required headers", seems we could instead say "Returning X bytes more than required for header 'Content-Type', this may affect your test performance" - thoughts? 

To me, the more user-friendly we can make the verification warnings the more framework devs can do their work withou having to consult the TFB team for guidance

**Comment by msmith-techempower** [comment]
@hamiltont Agreed - the wording could use a change.

**Comment by zane-techempower** [comment]
I think that section of the test can be improved. Another helpful feature would be to state specifically which header is missing rather than the general statement + warn that the code I specified is currently doing.

Letting devs know that the warn is for doing something that is likely reducing performace is definitely a user-friendly move.

**Comment by hamiltont** [comment]
Agreed on both - let's reopen this as an Enhancement request

**Comment by hamiltont** [comment]
Same concern with `Content-Type: text/plain; charset=UTF-8` and friends. header is correct but longer than required

**Comment by hamiltont** [comment]
Also, here's one more stack trace for verifying headers. Different problem, same big of relevant code

```
Server play2-scala-activate: [WARN] [04/25/2015 09:12:31.033] [New I/O worker #1] [EventStream(akka://play)] [akka.event-handlers] config is deprecated, use [akka.loggers]
  Response (trimmed to 40 bytes): "{"id":1792,"randomNumber":7486}"
WARNING:root:Verifying test db for play2-scala-activate caused an exception: 'NoneType' object has no attribute 'lower'
   FAIL for http://127.0.0.1:9000
     Caused Exception in TFB
               This almost certainly means your return value is incorrect, 
               but also that you have found a bug. Please submit an issue
               including this message: 'NoneType' object has no attribute 'lower'
     Traceback (most recent call last):
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 376, in verify_type
         results = test.verify(base_url)
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 53, in verify
         if any(v.lower() not in full_response.lower() for v in ('Server','Date','Content-Type: application/json')) \
       File "/home/travis/build/TechEmpower/FrameworkBenchmarks/toolset/benchmark/test_types/db_type.py", line 53, in <genexpr>
         if any(v.lower() not in full_response.lower() for v in ('Server','Date','Content-Type: application/json')) \
     AttributeError: 'NoneType' object has no attribute 'lower'
     See http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#specific-test-requirements
Accessing URL http://127.0.0.1:9000/queries?queries=:
```
