### ISSUE TITLE
nodejs /json is running lots of unrelated things

### ISSUE THREAD

**Issue by naugtur** [TechEmpower/FrameworkBenchmarks#1586]
in the /json case node is doing extra work that is only required in other cases. 
`res.end` call doesn't stop the current function, and the preparation code, as well as the other switch statement are invoked. After that the app attempts writing a 501 to a sent response (probably throwing some errors)

I didn't run it, but it is possible that after each request to /json an error is thrown and `cluster` module has to do the work to keep instances running. 

I suggest splitting the apps to separate modules and running different apps for different tests or at least implement a working router that doesn't run everything every time.

**Comment by zane-techempower** [comment]
You were quite correct, that was a textbook example of why not to use a switch statement. Requests to `/plaintext` and `/json` were falling through adding work without breaking anything at the testing level.

So far I have changed the routing to be safe and organized. I am considering adding Redis support, at which point I may break out each of the (would be 5) database configurations into their own files.

Would be nice to see a nodejs speed-up because of this!

**Comment by ngryman** [comment]
I am very surprised how poorly `node` performs in your benchmark. I can't believe that `ruby`, `java` or `lua` perform better in things like plain text responses, json formatting or anywhere else...

Some little things that could improve perfs:

- [ ] Your server only fits in one big switch case function, which will likely not be optimized by V8 in any way. You should at least put each route code in a function, invoked from the switch case.

- [ ] You execute a bunch of connections and work in the master process, which only monitors the cluster.
You should move everything in the the else branch, and also move that in a separate file required here.

- [ ] You require everything everytime, plaintext test for example does not need to setup connections to mongodb. This involves useless work with cpu & memory footprint. Instead you should sandbox each test.
Requiring external modules in JavaScript actually execute code right where they are required (with all he consequences it has like implicit initialization of the module). This is not the case for most languages that do it on the fly and where initialization is generally done explicitly.

- [ ] `return` before `else` is useless.

- [ ] This is executed for each request, it should not:
```javascript
var hello = {message: "Hello, World!"};
var helloStr = "Hello, World!";
var path = url.parse(req.url).pathname;
```

I'm sure that digging deeply enough and adopting better practices would really improve the perfs.

Your benchmark is quite popular and may be communicating false results because of the test code. I'm sorry to be cold, but when I see a Java fanatic linking to your benchmark saying "JVM is destroying node.js", it kinds of annoys me, I have to admit.

**Comment by zane-techempower** [comment]
@ngryman Thanks for stopping by, I have been improving the JS frameworks (nodejs so far) in PR #1635 . I have addressed some of the concerns voiced in this thread already.

> Your server only fits in one big switch case function, which will likely not be optimized by V8 in any way. You should at least put each route code in a function, invoked from the switch case.

That was terrible, the switch was actually dropping into another switch, I was surprised the tests were working at all. This has been fixed with some conditionals and should result in an easy speed up.

> You execute a bunch of connections and work in the master process, which only monitors the cluster. You should move everything in the the else branch, and also move that in a separate file required here.

This has been partially done, I will take you up on moving as much as possible (i.e. routing and db connection) into the else and then requiring that in. Good idea.

> You require everything everytime, plaintext test for example does not need to setup connections to mongodb. This involves useless work with cpu & memory footprint. Instead you should sandbox each test. Requiring external modules in JavaScript actually execute code right where it is required (with all he consequences it has like implicit initialization of the module). This is not the case for most languages that do it on the fly and where initialization is generally done explicitly.

Hopefully this will be taken care of with the other changes. I have separated out plaintext and json. The servers are given plenty of time to setup before requests are sent in so the initial setup time is not a concern. If connections to databases are being refreshed every request then that certainly is a problem. I think that putting the necessary `requires` into `http.createServer` will prevent database connections being established multiple times.

> `return` before `else` is useless.

Much of the Node code in the benchmarks was written ages ago :(

> Your benchmark is quite popular and may be communicating false results because of the test code. I'm sorry to be cold, but when I see a Java fanatic linking to your benchmark saying "JVM is destroying node.js", it kinds of annoys me, I have to admit.

I'm a JS fan myself and was dismayed to find that JS may be losing performance (i.e. looking worse than it may be). Round 11 will include many improvements specific to JS. Several JS frameworks like Hapi have had their versions updated, new frameworks like Sailsjs and Koa have been added. Additionally we are updating the versions of Node being used which should help as well.

**Comment by ngryman** [comment]
@zane-techempower Thanks for your detailed answer :)
I'm sorry if I was a little crude, I feel so bad now :sweat:
This comment on reddit just pissed me off at the moment.

Anyway good news you are taking care of refactoring this. I'm not a JS fanatic but I know by experience that `node` performs better than this. That's the problem with dynamic languages, code can become really messy / inefficient, really fast...

Good luck in the process.

**Comment by naugtur** [comment]
@zane-techempower I've got other things on my plate right now so I won't contribute directly, but if you want, you can `@-call` me when you have a working draft and I'll see if I can spot any issues there.

**Comment by zane-techempower** [comment]
@ngryman No problem man, the tests should, as much as possible, be representative of the true speeds of the frameworks/languages. Getting specific feedback greatly helps improvement between rounds.

@naugtur I am done with my changes in PR #1635, so please take a look. I think the files changed is a fairly clear picture of what I did https://github.com/TechEmpower/FrameworkBenchmarks/pull/1635/files . Any questions welcome. Any changes to be made will be done and included for round 11!

**Comment by naugtur** [comment]
I left some comments, hope they're helpful.
It's a change for the better, surely.
I'm not entirely sure about error handling in asynchronous callbacks, but it looks like it could cause trouble

**Comment by zane-techempower** [comment]
I see them and am working through, will post comments/responses in the PR when I'm done, great suggestions.

I think as far as errors: if there is anything wrong with the databases then the test should fail and stop, that's about the extent of the error handling here. So as long as the `err` is being throw at all (when there is one) that's good enough. I would say that if the db is running and connected to there will not be any errors; this isn't always the case as sometimes things fail to start-up in Vagrant or Travis.

**Comment by zane-techempower** [comment]
Closing, #1635 has been merged.
