### ISSUE TITLE
bash errors in config/benchmark_profile

### ISSUE THREAD

**Issue by jarnix** [TechEmpower/FrameworkBenchmarks#1588]
I'm using the vagrant image.
Every command that I try with toolset/run-tests.py returns an error, for example : (--list-tests does the same)

tfb@TFB-all:/FrameworkBenchmarks$ python toolset/run-tests.py --test beego --mode verify
config/benchmark_profile: line 2: $'\r': command not found
config/benchmark_profile: line 51: syntax error: unexpected end of file
CRITICAL: Loading config/benchmark_profile returned non-zero exit
FWROOT is /FrameworkBenchmarks
Usernames (e.g. --client-user, --runner-user, and --database-user) are required!

**Comment by msmith-techempower** [comment]
Currently, the vagrant setup does not work on Windows because of the line-endings issue.

Your best bet is to set up the environment manually using Virtual Box and a blank Ubuntu14 installation. You can find more information on how to do this [here](http://frameworkbenchmarks.readthedocs.org/en/latest/Development/Installation-Guide/)

**Comment by methane** [comment]
`git config --global core.autocrlf false` may help you.

**Comment by msmith-techempower** [comment]
I think I tried that (I use windows) and I couldn't get it working... I think.

One thing for sure, if this DOES work, it will only work BEFORE you clone the project.

**Comment by hamiltont** [comment]
@jarnix We'd be very interested to know if #1153 resolves this issue for you. Haven't had enough windows testers to know if that PR is helpful

**Comment by nbrady-techempower** [comment]
vagrant for windows is working now, without a symbolic link
