### ISSUE TITLE
Confusion about rules for database update test

### ISSUE THREAD

**Issue by denkab** [TechEmpower/FrameworkBenchmarks#1622]
http://frameworkbenchmarks.readthedocs.org/en/latest/Project-Information/Framework-Tests/#database-updates

In a way, rules 9 and 10 seem to be in conflict. It is very typical that individual updates in a batch for traditional RDBMS (and NoSQL is not different if similar optimization concepts are followed) can not be separated into individual transactions.

Possibly, a clarification and revision of existing code is needed to bring all implementations into compliance.

**Comment by zapov** [comment]
It's also very typical to do selects in batches, at least on DB which support it, such as MS Sql Server. And is unfair to disallow patterns and frameworks which have workarounds on other DBs.
I find it highly unlikley that the rules will be fixed, but at the very minimum tests should be renamed to multiple roundtrips instead of multiple queries. That should remove any confusion

**Comment by msmith-techempower** [comment]
The rules in question have been updated to better represent their meaning.
