### ISSUE TITLE
Logging improperly sending all to out.txt

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#1655]
Seems that all output is sent to `out.txt` and nothing really is sent to `err.txt`

**Comment by hamiltont** [comment]
[That one is on me](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L254)

It was actually intentional - I found that having two separate files was not very useful for debugging purposes when something went wrong, and when things go right there are only 2-3 lines in these files so mixing them was not a big deal. Also there is a code maintenance and runtime resource benefit to having only one thread watching the process for IO instead of two, but that's a fairly minor concern. My main thought was just that it was annoyingly hard to rebuild the full picture of what happened by stitching err.txt and out..txt back together in the correct order

**Comment by msmith-techempower** [comment]
I am going to repurpose this task - I think we should do the following: 

1. Remove `err.txt` entirely; it is unused now
2. Add a `verification.txt` that only contains the verification stage output
3. Add a `[test type].txt` for each test type that only contains the output for that everything beginning with "Benchmarking [test type]" until that test is done.

This assists with a few different things, but mainly it makes testing and benchmarking easier for me >_<

**Comment by cjnething** [comment]
Resolved in #1991
