### ISSUE TITLE
WRK timeout value is breaking benchmarks

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#2005]
Currently, the scripts in `toolset/benchmark/framework_test.py` ([example](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/benchmark/framework_test.py#L48)) are breaking in wrk4; change the timeout to a more realistic number (maybe 8?).

**Comment by bhauer** [comment]
My understanding of the wrk timeout feature is that it monitors request durations and those that exceed the timeout length will be counted as "timed out."  However, a timed-out request is not interrupted and is permitted to complete normally.

We do not use the resulting count of timed-out requests since we are (presently) primarily concerned with throughput and secondarily with latency.  If we were to make latency a primary focus, we would structure the use of wrk differently, maybe using the timeout value and maybe not.

Presently, although the resulting count of "timed-out" requests is captured by wrk in the raw output, we do not consume or render it.  We believed that capturing this information was not measurably impacting wrk or the results we care about.

However, considering that this issue suggests there is some overhead in wrk related to monitoring requests that have timed out, I recommend keeping it low.  **8 seconds does seem reasonable.**

**Comment by methane** [comment]
I agree.

On 256 concurrency, deadline performance is 256 / 8 = 32 req/sec.  (plaintext
We can't measure throughput lower than 32 req/sec.  But we can use lower concurrency result when framework is slow.

(In case of plaintext benchmark, minimum concurrency is 256 and one connection has 16 pipelined request.  Deadline performance is 256 * 16 / 8 = 512 [req/sec].)
