### ISSUE TITLE
round13 preview: ringojs shows up twice in results

### ISSUE THREAD

**Issue by oberhamsi** [TechEmpower/FrameworkBenchmarks#2203]
in all but the plaintext and JSON test-results, ringojs is listed twice as Test#191 and Test#189 (the additional ringojs-conv Test#190 is to be expected). The two results are very close and it seems the same setup was run twice.

I can't tell what's wrong with the code: there's only two ringojs folders and the benchmark_config.json seems fine.

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/JavaScript

**Comment by knewmanTE** [comment]
If you mouse over the two tests, you can see that one of them is for "ringojs" and one of them is for "ringojs-raw." This explains why you're not seeing double occurrences of plaintext or JSON, because those tests are only specified in "ringojs." I believe you're right, though. If you look at the benchmark_config, they are both using the same setup script and hitting the same URLs, and since there are any other DBs or ORMs to test with, I think we can safely get rid of the ringojs-raw test and just run them all through the default.

**Comment by knewmanTE** [comment]
Addressed in #2206

**Comment by LadyMozzarella** [comment]
See #2206
