### ISSUE TITLE
Lwan used with SQLite, better to use it with MySQL

### ISSUE THREAD

**Issue by taggedboy** [TechEmpower/FrameworkBenchmarks#2209]
I noticed one thing. The Lwan is used with SQLite, may be this is the reason for so poor single query and multiple query performance. Better to use it with MySQL or PostgreSQL.

**Comment by bhauer** [comment]
We do not yet intend to render results from tests that use SQLite.  Doing so avoids the database round-trip that is expected for the database query tests.

In fact, performance using SQLite is typically dramatically higher than MySQL or Postgres precisely because there is no network communication with an external server.  But that is not what we had in mind when we constructed these test types.  A future test type may be implemented to allow for local/in-process database engines such as SQLite.

**Comment by nqzero** [comment]
@bhauer is the only problem with sqlite that it's in-process as opposed to client-server, and as such avoids the network round-trip ? is there any documentation or official statement describing what is required of a database to be acceptable to use ?

**Comment by msmith-techempower** [comment]
It isn't laid out in direct terms, but from [the rules](https://www.techempower.com/benchmarks/#section=code):

> Except where noted, all database queries should be delivered to the database servers as-is and not coalesced or deduplicated at the database driver. In all cases where a database query is required, it is expected that the query will reach and execute on the database server. However, it is permissible to pipeline traffic between the application and database as a network-level optimization. That is, two or more separate queries may be delivered from the application to the database in a single transmission over the network, and likewise for query results from the database back to the application, as long as the queries themselves are executed separately on the database server and not combined into a single complex query.

Which suggests implicitly that the database must be running on a separate server.

We have also laxly enforced a loose rule of "the database should persist data to disk" in the past, but I'm not sure we have a firm stance on this; we may need to reevaluate.
