### ISSUE TITLE
JSON serialization on the Query tests

### ISSUE THREAD

**Issue by CreaoticX** [TechEmpower/FrameworkBenchmarks#2262]
I have a question about the methodology on your Query tests.  Both tests require that the output be delivered in json.  I assume this is for validation purposes and you need a consistent method of output to validate.  However, wouldn't this necessarily bias these tests against any platform that already did poorly in the json test?

So I was wondering if it is acceptable to output the results in a json format without actually running a json serialization function.   Something like:

    print '{'+world.id+':'+world.randomNumber'+'}'

Obviously this wouldn't apply to the JSON test because I assume you're actually trying to test the json serialization function.  However, since on the query tests I assume you're really after the query speed and not the json serialization speed, this would produce more accurate tests in any language that does poorly with json serialization.

Thanks

**Comment by bhauer** [comment]
Hi @CreaoticX.  Thanks for the thoughtful question.

The query tests predate the implementation of automated validation tests.  So while you are correct that today the JSON format gives us a convenient standard for our validation, that wasn't the original intent.  Originally, we simply wanted implementations to render results in JSON because it's one of the two most common outputs for a web application (the other being HTML, which is used in the Fortunes test type).

We want all tests to incur the costs of web application fundamentals (such as request routing, headers, and response encoding).

It is true that a platform that has low-performance JSON serialization will see that performance impact in the JSON, single-query, multi-query, and updates tests, all of which produce JSON output.

For the query tests, I suspect very few frameworks/platforms will see JSON serialization impact performance to a degree greater than the queries themselves.  In other words, to just throw some very rough numbers out there, I would expect the queries to account for ~95% of the work and JSON serialization less than ~5%.

Of course, not all platforms are created equal so it is plausible that on some platform, JSON serialization could be a significant bottleneck.

That said, I would prefer to leave the rules as-is.  Not that I anticipate you or anyone else has this in mind, but if we remove one part of the web application fundamentals—such as JSON response encoding—for the query tests, it is conceivable that someone would suggest that we could also remove the need for standard request routing or URL query parameter processing or something else.  In other words, any part of the web stack that is not immediately pertinent to the test type would be (potentially) up for debate.

I hope that makes sense and appreciate your input!

**Comment by CreaoticX** [comment]
@bhauer I get your point.  And to be clear I wasn't saying that the response and the headers shouldn't still be done in JSON.  My point was more in how you get there.  To use an example to be a little more clear.  PHP >5.4 has the `JsonSerializable` interface built in.  It basically lets you define how an object is converted to JSON by returning an array of the parameters to be serialized instead of the object itself.  The benchmarks I've seen on this resulted in a 17% improvement using json_encode.  None of the php tests that I looked at use this.  I was going to go in and add this interface to the tests, because if your testing for speed it seemed to make sense to use the best the system has to offer.  

However, my next thought was, if you're going to add an extra function to convert it to an array, why not just use string concatenation to output a json string directly, which I would assume would be faster.  

So based on your response, adding the `JsonSerializable` interface to php objects would be ok because it is still using `json_encode` but creating a `toJson()` function that simply outputs the object as a json string would not be.  Am I understanding that correctly?
