### ISSUE TITLE
Java/Permeagility not communicating with database server

### ISSUE THREAD

**Issue by knewmanTE** [TechEmpower/FrameworkBenchmarks#2346]
I noticed today that Java/Permeagility is [creating a local document database with OrientDB](https://github.com/PermeAgility/FrameworkBenchmarks/blob/master/frameworks/Java/permeagility/src/dbSetup.java). Though on the surface, OrientDB may seem similar to MongoDB, in our production environments, we have 3 separate machines: one for running the framework, one for generating the client load, and one for hosting the databases. If you check the test requirements for the [Multiple Database Queries](http://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Framework-Tests/#multiple-database-queries) test, it specifies that "This test is designed to exercise multiple queries, each requiring a round-trip to the database server."

In order to comply with the rules of the suite and be as fair as possible to the other frameworks, we should either update Permeagility to communicate with the database machine using one of the existing databases (MySQL, Postgres, MongoDB, etc.)  or disable its database tests.

cc @glennirwin

**Comment by glennirwin** [comment]
PermeAgility is designed around and tightly integrated with OrientDB's database and can use the built-in embedded database or a remote OrientDB database.  If there was a remote OrientDB database available configured for the benchmarks, I could hook it up to that but hooking it up to another database is not really what it is designed for other than to load data from other databases. 

As database functions are an important part of this framework,  I would prefer to leave the database queries in the benchmark unless this is considered a major issue.  I don't think this gives it an unfair advantage as all database functions are executed on the web server consuming resources that could otherwise be used to respond to requests quicker. 

So are you saying the database tests must use one of the supplied databases?  Maybe I misunderstood the documentation for the database tests.  The software has a connection pool of database connections and uses SQL to access its database so I figured it was pretty close to how the other database tests would be implemented.

**Comment by knewmanTE** [comment]
@glennirwin the main issue is that the database tests are used to simulate a scenario where a database is hosted on machine A and machine B is requesting information from it. If the database is already on machine B, then it isn't representing the same use-case.

We're definitely not opposed to OrientDB tests. It sounds like configuring a remote OrientDB database that PermeAgility can use is the best solution in this case, since we still want PermeAgility to perform at its best!

If you're interested in adding it in, I'd recommend taking a look at the [database.sh setup script](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/database.sh), as that is where the other databases are initialized and installed and it's probably good template for adding any new databases. One thing that might be a bit confusing about the script is that it mentions a lot of files (like MongoDB's `create.js`). These files are located [in the config directory](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/config/) and there is a line [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/toolset/setup/linux/installer.py#L32) that uses the script [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/config/database_sftp_batch) to move certain files over to the database machine when the `toolset/run-tests.py --install database --install-only` script is run.

**Comment by nbrady-techempower** [comment]
Now that the toolset has changed some, some of this doesn't apply. Welcome to create a OrientDB setup in the toolset the same way mongo, postgresql and MySQL are done
