### ISSUE TITLE
Cannot run nodejs-postgres without running nodejs

### ISSUE THREAD

**Issue by rkraman** [TechEmpower/FrameworkBenchmarks#2482]
Downloaded the latest code today and created a vagrant development environment and ran the test for nodejs-postgres
**toolset/run-tests.py --test nodejs-postgres**
This gives an error for MongoDB and the test fails and stops.
The output log file can be found here:  http://sprunge.us/XUQC

Deleted the vagrant image, created a new one and this time first ran the default test
**toolset/run-tests.py --test nodejs**

That ran successfully.  Later I **ran toolset/run-tests.py --test nodejs-postgres**
and everything worked fine now.
Need to remove the dependency for MongoDB.
-rkraman

**Comment by nbrady-techempower** [comment]
At the time this implementation was written, our test suite had all databases already loaded and accepting connections. We recently changed this so that frameworks would only load the databases they need and also make sure there was fresh starting data in the db. Because there's only 1 `package.json` and imports are happening for all dependencies on all tests, each test seems to be testing for other db connections even if not using it. Rather than rewrite the framework implementation, which we leave up to contributors/maintainers, loading all dbs for each test is a quick fix. See #2484
