### ISSUE TITLE
Upgrade kernel version in Vagrant configuration

### ISSUE THREAD

**Issue by mwpastore** [TechEmpower/FrameworkBenchmarks#2496]
I would like to see us `apt install linux-hwe-virtual-trusty` somewhere in the Vagrant configuration to bring the kernel up to 4.4-longterm. The 3.13 kernel that comes with ubuntu/trusty64 is EOL. Travis appears to be running with this kernel as well.

**Comment by nbrady-techempower** [comment]
@mwpastore Upgrading the kernel on vagrant would add several minutes to the installation, and I'm not sure what benefits it would provide in that environment since this would be primarily for security/hardware? There might be an image from vbox set up this way; I can look in to that. Nonetheless, a move to 16.04 and the xenial kernel *shouldn't* be too far off.

ping @msmith-techempower for thoughts

**Comment by mwpastore** [comment]
I'm sure there were probably one or two improvements to userspace performance and stability between 3.13 and 4.4. :smile: The big feature for me is gaining the MemAvailable key in /proc/meminfo, which can be used to scale [Puma](http://puma.io/) workers to the available memory.

**Comment by msmith-techempower** [comment]
Oof... would this be part of the prerequisites file? I am always hesitant to do anything that cannot be easily included as a part of our build-up; our setup instructions already include too much "now type in these commands into bash!"

**Comment by nbrady-techempower** [comment]
@mwpastore http://www.phoronix.com/scan.php?page=article&item=linux-44-19way&num=1 I'd be interested in your thoughts on this.

@msmith-techempower It could be included in the vagrant boostrapping or common, but I'm still :shrug: I don't think anyone is doing real performance testing with our vagrant set ups, are they?

**Comment by msmith-techempower** [comment]
Specifically, if we are going to do it to **an** environment, we should do it to **every** environment in a general way.

For example, if there is an update to the network stack as a part of the kernel update, then the results would differ from environment to environment.

Foot down: if we're going to do it, it should be done everywhere.

**Comment by mwpastore** [comment]
@msmith-techempower I think it would just be in the Vagrantfile somewhere, like when we do [`apt-get install git`](https://github.com/TechEmpower/FrameworkBenchmarks/blob/f9c9793a4b8e1f3006405db6ae2a4cf9a07983da/deployment/vagrant-common/bootstrap.sh#L94), add `linux-hwe-virtual-trusty` as well. It would require a reboot (or reload) to be effective, but the VM would work fine on the old kernel until that happens, if it happens.

@nbrady-techempower No, I don't think anyone is doing real performance testing under Vagrant. I am more interested in stability, consistency with Travis, and this one feature that is helpful to me. 😛 I'll read that Phoronix article you linked.

**Comment by nbrady-techempower** [comment]
The official vagrant trusty box was just updated in May and it still hasn't made the jump to the new kernel. Since travis, vagrant, and our SC boxes are still ~3.13, I'm going to close this.

That's not to say I'm not keeping an eye on it, but if any work needs to be done to the toolset, or all the environments, I'd rather it be to get to 16.04 (Which I plan on taking another deep look at soon)
