### ISSUE TITLE
Vagrant toolset problem/instability

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#2645]
Problem:
I've noticed the following problem with the `new` reworked Vagrant environment. After starting a VM with `vagrant up` the first test that is using a database fails. If executed again all is fine. I've tested with PostgreSQL as database.
The console log and the results directories are here: https://github.com/zloster/logs/tree/master/FrameworkBenchmarks/vagrant-instability

**Comment by nbrady-techempower** [comment]
@zloster I've done this twice and was unable to reproduce. If you can, let me know if this is still an issue and if so, what your host os is.

**Comment by zloster** [comment]
@nbrady-techempower There seems to be additional condition for this to happen:

The build of the framework have to be fast or already executed in the VM before the `vagrant up` - in the [provided logs](https://github.com/zloster/logs/blob/master/FrameworkBenchmarks/vagrant-instability/console-log.txt#L407-L408) the `gemini-postgres` build has finished after 2 seconds.

```
Setup gemini-postgres: BUILD SUCCESSFUL
Setup gemini-postgres: Total time: 2 seconds
Setup gemini-postgres: Resin/4.0.48 launching watchdog at 127.0.0.1:6600
Setup gemini-postgres: Resin/4.0.48 started -server 'default' with watchdog at 127.0.0.1:6600
Setup gemini-postgres: Status: Poll: None, Port 8080 bound: True, Time Left: 1:44:16.578171
Setup gemini-postgres: Bound port detected on 8080
INFO:root:Executed start_postgresql.sh, returning 0
INFO:root:Sleeping 60 seconds to ensure framework is ready
```

I'm using the VM on a underpowered machine - the CPU is a 6 Watt [Intel Celeron N3150](http://ark.intel.com/products/87258/Intel-Celeron-Processor-N3150-2M-Cache-up-to-2_08-GHz). The host OS is Ubuntu Server 14.04.

Maybe if you limit the available CPU resources for your VM it will be easier to reproduce.

**Comment by nbrady-techempower** [comment]
@zloster Ah, I see what's happening here. When you said `vagrant up` I was assuming it was being created for the first time. Instead, you're halting and then bringing back up an existing vm. Because the installs directory exists and the databases and framework were presumably already installed, the db installation step is skipped, which I believe also makes sure the db services have started. I'll work on a toolset change that makes sure the services are started even if the database is installed. Until then, a quick fix would be to remove the installs directory. Thanks for pointing this out.
