### ISSUE TITLE
Fix java spark plaintext

### ISSUE THREAD

**Issue by dessalines** [TechEmpower/FrameworkBenchmarks#2792]
I noticed that the java spark plaintext is having errors, yet the JSON one is not, and is showing faster than many other frameworks.

**Comment by nbrady-techempower** [comment]
Thanks @dessalines Do you have something specific you can point to that may be causing the errors with Java Spark? Please feel free to look through the logs for the round at: http://tfb-logs.techempower.com/round-14/

The Spark plaintext implementation hasn't been touched in some time. Spark plaintext performed better than in Round 13, even though it includes some errors.

I'll probably draft up a larger issue with each of the frameworks that produced errors for Round 14. Since there actually were a good number of them, I'd prefer to only open issues about them if there is a little more detail regarding the potential problem.

If you have any ideas, please feel free to open another issue or a pull request with some updates! Thanks! :)
