### ISSUE TITLE
How about adding a "rank" column to results table

### ISSUE THREAD

**Issue by rainchen** [TechEmpower/FrameworkBenchmarks#2927]
How about adding a "rank" column to results table.

For example:

![frameworkbenchmarks-with-rank-demo](https://user-images.githubusercontent.com/71397/28608070-7584fed6-7211-11e7-9175-6bdc0f7f5d79.png)

BTW, I done this with one line of js code:

```
$("#bar-fortune table tr").each(function(i, tr){ $(tr).prepend('<td>'+(i > 0 ? i : 'Rank') + '</td>') })
```

**Comment by bhauer** [comment]
Despite my [reservations about rank ordering](https://groups.google.com/d/msg/framework-benchmarks/ZR_os9nQs4M/6XpD98q-AQAJ), I have added this feature to the results web site.  You will see a small, faint rank order to the left of the framework names.

In the conversation linked above, I wrote:

>We often recommend that readers consume results not by the fine-granularity of rank ordering, but rather using rough tiers of performance to help their decision-making process.  All else being equal, selecting any high-performance framework is likely to result in roughly the same real-world performance.  For example, in Round 14's Fortunes results, you can imagine a high-performance tier composed of results of 80,000 rps and up, a mid-performance tier between approximately 18,000 and 80,000 rps, and a low performance tier at 18,000 or lower.  I plan on elaborating on this in a future blog entry, but the basic gist is that coarse-granularity is more effective as an evaluation tool than specific rank ordering.  I do however appreciate the joy of breaking some threshold such as being in the top 3.

Since I prefer the notion of general performance tiers more than specific rank ordering, I might try out a rendering for the tiers.  A basic approach would divide the full span of performance coverage into N tiers and then render horizontal separators at each transition point in the table.

Something like this:

![tiers](https://user-images.githubusercontent.com/777068/40451894-f4fcda1a-5e94-11e8-89ab-1594c949297e.png)
