### ISSUE TITLE
Re-enable non-Docker deployments

### ISSUE THREAD

**Issue by Tenchumaru** [TechEmpower/FrameworkBenchmarks#3514]
Since commit 6fce84a, WIP: Dockerify everything (#3457), it appears Docker is now required. There was discussion about its benefits and drawbacks in issue #2943 last year, but no discussion about why there was a final decision to make it the only deployment model. I don't see anything about this on the [Toolset Enhancement Roadmap](/TechEmpower/FrameworkBenchmarks/projects/1). I have an interest in validating the results and creating new tests on dedicated hardware; Docker is neither necessary nor desirable for my situation. As a result of this change, I am unable to use the master branch and have reverted to the round15 branch.

On separate hardware, I tried using the master branch but the [documentation](https://frameworkbenchmarks.readthedocs.io) is woefully out of date. For instance, the scripts mentioned in the [Benchmark Suite Setup](https://frameworkbenchmarks.readthedocs.io/en/latest/Benchmarking/Getting-Started-Benchmarking/#benchmark-suite-setup) section are nowhere to be found, I assume because they no longer apply to the new Docker-only configuration. I have no idea how to run a test that uses multiple machines (i.e., one for `wrk`, one for the application server, and one for the database server). I suppose this is an issue for the [documentation site](https://github.com/TechEmpower/TFB-Documentation).

Perhaps I am mistaken about non-Docker deployments. If so, then it's a documentation issue and I will file an issue there. Otherwise, I request re-enabling non-Docker deployments.

**Comment by RX14** [comment]
You can't reasonably maintain both docker and non-docker deployments. It's one or the other.

What exact problems do you have with using docker?

**Comment by Tenchumaru** [comment]
My exact problems with Docker are (1) it is now required and (2) there is insufficient documentation.

As for (1), as I said above, I don't need it and I'd rather not use it; it's another dependency to install. Its affect on the performance of these benchmarks is perhaps immaterial if it affects all tests equally. It's unfortunate that maintaining both isn't reasonable. I found no documentation in any issue or roadmap for how or why this decision was made but, apparently, there is no turning back. I am now faced with either staying with branch `round15` or starting to use Docker.

Which brings me to (2): there is no documentation for the new deployment model. As I said above, I have no idea how to deploy the benchmark to use multiple machines or how to create my own tests.

**Comment by RX14** [comment]
Yeah, the second part is very unfortunate, however it should be easier than before, once the new setup is documented. You'll have to wait for the techempower guys for docs though :(

**Comment by nbrady-techempower** [comment]
@Tenchumaru we'll be happy to walk you through a 3 machine setup with docker. Pinging @msmith-techempower since he just did it recently.

We've had discussions both publicly and internally about moving completely to docker. See discussions here and our [blog](https://www.techempower.com/blog/) We're doing a thorough review of the docs, which will be updated soon.

For any single machine dev work, either using vagrant or your local machine, the [readme](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/README.md) has been updated.

**Comment by msmith-techempower** [comment]
We did some internal benchmarking against a few select high performers to see the 'cost' of using Docker with `--network=host` versus running the application natively, as previous iterations of the toolset did, and we found deltas in performance that are ostensibly zero (there is always noise in the benchmarks of usually <1% and we saw similar numbers using Docker). So, after internal discussions with the team, I decided to explore, and ultimately we have done so, moving the suite to leverage Docker.

There are a LOT of reasons for doing so, but here's the short list:

1. `fw_depends` was non-intuitive in design and use for anyone without intimate knowledge of our toolset and its ecosystem.
2. TFBReaper was a glorious but simple-to-the-point-of-being-dumb solution to a problem that Docker (and other container technologies) have solved in a more robust and standardized way. For context, the problem to which I refer is being able to keep track of all processes and forked processes and be able to stop them ultimately. This is a non-trivial task and while I am proud of TFBReaper (having written him), it simply was too simple a tool for us to rely on and edge cases kept cutting us.
3. The suite used `ssh` for communication between the three machines (or one machine, in that setup), and that has long held us in a position of requiring `ssh` on the host systems (which for a long time meant 'Linux-only'), but Docker provides a 'host' mode which allows communications over tcp using its own protocol. With the Docker implementation, we can now communicate with every machine in the setup without the requirement of `ssh` and that moves us towards being host OS agnostic, and that is a good thing.
4. Every application implementation was required to be able to start on the host machine and used a bash script to do so (which also meant 'Linux-only'), but with Docker we can be host OS agnostic, and that is a good thing.
5. The toolset has for a long time strived to ensure that installations were **not** global and that any machine could treat installations as sandboxed. This was never true, and we were never able to meet that goal, which meant that fresh OS installs were the only way to ensure that one benchmark was equal to another. Docker affords us the luxury of installing in images, which **is** sandboxed. The host system is untouched and in general it means that installation of software for test implementations is both easier and straight-forward to understand as an auditor at pull request time.
6. Test times on Travis-CI, our continuous integration testing provider, are lowered **significantly** by leveraging installs from Docker and pre-published base images.
7. We are still in the middle of this, but the next goal is to remove most-or-all of our dependency dockerfiles in favor of every test implementation `FROM`ing their own base image (read: instead of using 4-5 base images in our repository and our toolset chaining these intelligently, the test implementation should just say `FROM python:3.4.1` and build/run its python app). This would allow us to implement 'versions' of those test implementations in `benchmark_config.json`s and publish those images, which would afford the actual benchmarking to not waste time building and instead simply pull the published image, start a container, benchmark it, and discard that image. This could potentially save us **DAYS** in benchmarking and allow us to turn out 'rounds' more frequently and accurately (the biggest goal of all).

The issue with our documentation is known and improving day-to-day. Luckily, Docker also reduces the complexity of running our toolset immensely, so the documentation is largely captured in our `README.md` (instead of readthedocs, for instance). We will continue to iterate this as issue arise.

However, as has been expressed in this thread we have neither the developer bandwidth nor the interest in supporting, what at this point is, the legacy version of the toolset.

[The documentation](http://frameworkbenchmarks.readthedocs.io/en/latest/Development/Installation-Guide/) has everything required to get a triple-machine setup working on the legacy version except for one thing: after you run `source toolset/setup/linux/prerequisites.sh` you have to then run `tfb --init`, which will initialize the database and ensure that `wrk` is installed and ready on the client machine. Everything else in that documentation, for now, is accurate.

If you are still finding difficulty in getting that commit running, feel free to stop by [Freenode](https://webchat.freenode.net/) `#techempower-fwbm` and I can help troubleshoot.

**Comment by Tenchumaru** [comment]
Thank you, both of you, for your thoughtful and complete responses. I haven't been a fan of Docker because I've never used it and I've heard enough horror stories about it. Nonetheless, based on your reasoning, I believe it works very well for your situation. (I completely missed mention of Docker in your blog because I was scanning the titles on the right and didn't see that you discussed it in the text of your most recent entry on the left. Silly me.)

At some point, after I complete my current analysis, I will revisit your `master` branch, gladly using Docker. I appreciate you making your results, as well as the underlying implementations and the ability to independently validate them, publicly available. I believe this will also give me a good introduction to a good use case for Docker.

Here are a couple of minor issues:
1. `source toolset/setup/linux/prerequisites.sh` causes several problems in the terminal, at least with `bash` on Ubuntu 16.04. Running `./toolset/setup/linux/prerequisites.sh` followed by `source /etc/profile.d/tfb.sh` instead seems to work fine.
2. `tfb --init` fails since `--init` is not a recognized parameter, at least in the `round15` branch. However, since I'm not currently concerned with the database-related test cases, I've had little difficulty getting working those test cases that concern me. I've used, for instance, `tfb --test rapidoid --type json --sleep 15 --mode verify` to ensure everything is working.
