### ISSUE TITLE
Should These Tests Be Stripped?

### ISSUE THREAD

**Issue by emilypi** [TechEmpower/FrameworkBenchmarks#3671]
The functionality in question is in regards to several Scala framework tests:

-  [this line](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Scala/akka-http/src/main/resources/application.conf#L21) in the [akka-http](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Scala/akka-http), uses highly nonstandard jdbc options to tune for a specific kind of request pattern.

- In one [play-framework benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Scala/play2-scala/play2-scala-anorm/conf/application.conf#L57) these config values explicitly state that they have tuned the benchmark to known Techempower box stats, adjusting accordingly.

- In another [play-framework benchmark](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Scala/play2-scala/play2-scala-netty.dockerfile#L5) there are nonstandard JVM options added to tailor performance, which one would never use in production in a general setting (not without a great deal of domain knowledge and performance testing)

So my question is, what is the line at which tests are stripped from the benchmark? What are the admissible bounds for tuning the benchmarks to work optimally with Techempower's vmware choices?

Thanks for your response!

**Comment by michaelhixson** [comment]
This doesn't match my intuition of what "Stripped" test implementations are.  To me, an important quality of Stripped is that it's the opposite of Realistic.  A Stripped implementation does things for the sake of performance that no one would ever do in a real application.  A Realistic implementation might also do tuning, but it's the same sort of tuning you'd do in a real application.

Tuning exclusively for one particular environment is unfortunate in our case (are you tuning for Azure, did you update when we moved away from ServerCentral, how can the reader apply this to their own environment), but I'd still call it Realistic.

Here are some thoughts about the individual items you pointed out:

> this line in the akka-http, uses highly nonstandard jdbc options to tune for a specific kind of request pattern.

The reasoning behind that particular set of MySQL+JDBC options has been lost in time.  At this point it's been copy and pasted into too many places.  `cachePrepStmts=true` and `useSSL=false` stick out to me as important and doing something that affects performance measurably, the rest might not be doing anything.  This same set (or a similar set) of MySQL-specific options even appears in some PostgreSQL connection strings...

> In one play-framework benchmark these config values explicitly state that they have tuned the benchmark to known Techempower box stats, adjusting accordingly.

I really like this one!  It's wrong because our benchmark environment changed, but it explains how that setting should be tuned for any given environment.  I wish we had more comments like this.

> In another play-framework benchmark there are nonstandard JVM options added to tailor performance, which one would never use in production in a general setting (not without a great deal of domain knowledge and performance testing)

I'm not a fan of these big sets of JVM options, mostly because I worry that they get copy and pasted like those JDBC options and were never measured.  I bet we could simply remove most of these options without affecting results.  But I'm not personally motivated to go do that.  As a reader of the code, I've become used to ignoring these options as fluff / insignificant boilerplate.

**Comment by emilypi** [comment]
Thanks for explaining @michaelhixson 

Mostly I just want to see where the bar is for what's considered strippable offenses. You definitely answered the question 😄
