### ISSUE TITLE
Filter functionality broken for continuous results

### ISSUE THREAD

**Issue by kelunik** [TechEmpower/FrameworkBenchmarks#3693]
When I visualize results from https://tfb-status.techempower.com/ via the link, the filter functionality does simply nothing when applying the filter. It works fine with the rounds when I'm not importing data from `tfb-status`.

**Comment by michaelhixson** [comment]
The fix was deployed.  This issue should be fixed, and so should the issue where it was "forgetting" the runid in the URL when you clicked between test types.  Now if you visualize results from tfb-status, then you click on a new test type and/or apply filters, the URL should retain everything necessary such that refreshing the page or sharing the URL works as expected.

**Comment by kelunik** [comment]
Fix confirmed. :tada:
