### ISSUE TITLE
Wrong cached queries test parameters

### ISSUE THREAD

**Issue by volyrique** [TechEmpower/FrameworkBenchmarks#3804]
[The documentation](https://frameworkbenchmarks.readthedocs.io/en/latest/Project-Information/Framework-Tests/#caching-work-in-progress) states that the parameter values for the cached queries test are 1, 10, 20, 50, and 100; these were also the values used in [run 8de314d3-b970-4295-a3ca-3682f3905a3b](https://tfb-status.techempower.com/results/8de314d3-b970-4295-a3ca-3682f3905a3b) (the last one before the test became broken). However, the [last successful run](https://tfb-status.techempower.com/results/60fab9eb-a5ad-49cb-aefe-24ad0f377122) uses 16, 32, 64, 128, 256, and 512. Is that intentional?

**Comment by zloster** [comment]
(Several months later)...

**Comment by zloster** [comment]
(Several months later)...
https://tfb-status.techempower.com/unzip/results.2019-03-16-06-30-33-053.zip/results/20190312173754/ulib-postgres/cached_query/raw.txt
The problem is still here.
Also _only_ the 16 queries test case is not able to saturate the 10 Gb/s network. All the other (32, 64, 128, 256, 512) are hitting the transfer limit of 1.08-1.09 GB/s.
