### ISSUE TITLE
Consider reclassifying actix-raw as stripped

### ISSUE THREAD

**Issue by bhauer** [TechEmpower/FrameworkBenchmarks#3845]
Based on [feedback from bluetech at Reddit](https://www.reddit.com/r/rust/comments/8p6c6w/techempower_benchmarks_round_16/e0a46pm/), we should consider reclassifying the implementation approach of `actix-raw` as Stripped.  Assuming we agree on review, let's please do that.

**Comment by bhauer** [comment]
@fafhrd91 Can I get your opinion on this?

**Comment by fafhrd91** [comment]
I'd leave It as is, I am planing to use actix in this form in production.
also several other benchmarks uses same approach

**Comment by seanmonstar** [comment]
It definitely seems *more* stripped than most of the "realistic" frameworks listed, for these reasons:

- It strips the concept of provide a status code and list of headers, instead having the user write compile time strings to the socket, like `b"HTTP/1.1 200 OK\r\n"`, `b"Content-Type: text/plain\r\n"`, etc.
- It has the user verify they've written the body correctly.
- It uses a private/internal API, `HttpHandlerTask`. As it is explicitly removed from the docs, it appears to be exposed/used explicitly for this benchmark, which the "Stripped" classification mentions.

It **does** use the request parsing / handling part of actix-web, so I agree it's not *completely* stripped. Still, it doesn't seem like something that a user would be recommended to do, especially since the performance improvements are minuscule.

**Comment by fafhrd91** [comment]
here is real use case, 
we have websockets proxy, we use request parsing from actix-web, then we bypass all high level
frameworky part and then use buffer directly after successful upgrade. and this is real use case that will go to prod soon.

and it is marked as platform and micro framework

**Comment by fafhrd91** [comment]
@bhauer i suggest to close this ticket. all api are public now. also if consider actix-raw as stripped we would need to mark many other benchs stipped as well, for example aspcore.
