### ISSUE TITLE
Gather data for the Resin performance - with and without its JNI library

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#4083]
I'm seeing the following log from all projects that are using Resin when the server is starting:
```
gemini-postgres: [10:22:27.020] Unable to find native library 'resin_os' for com.caucho.loader.ClassEntry. Resin expects to find this library in:
gemini-postgres:                  (Unix) /resin/libexec64/libresin_os.so
gemini-postgres:                On Unix, run ./configure --prefix=`pwd`; make; make install.
gemini-postgres:                The JVM exception was: java.lang.UnsatisfiedLinkError: no resin_os in java.library.path: [/resin/libexec64, /usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
```
[Here is a link to an actual TravisCI run](https://travis-ci.org/zloster/FrameworkBenchmarks/jobs/436526423#L5679-L5682).

I'm guessing that `./configure --prefix='pwd'; make; make install` should be added to the `.docker` files. All of them seems to be mentioned in PR #3604.

**Comment by michaelhixson** [comment]
> I'm guessing that `./configure --prefix='pwd'; make; make install` should be added to the `.docker` files. 

We removed this on purpose in https://github.com/TechEmpower/FrameworkBenchmarks/pull/3434 because it was a frequent point of failure and maintenance time sink.

If the only downside is that we see that warning in the logs, I'd prefer to leave it be.  I'm ok with changing it back if it fixes other problems though.

**Comment by zloster** [comment]
[Resin documentation](https://caucho.com/resin-4.0/admin/starting-resin-command-line.xtp#.configureoptions) recommends the JNI code for maximum performance. I'm curious is there a difference and how big it is.
Any chance to get the numbers for some project with and without the JNI code (Gemini for example)?

**Comment by michaelhixson** [comment]
> Any chance to get the numbers for some project with and without the JNI code (Gemini for example)?

Sounds reasonable.  We generally don't do one-off manual tests in the Citrine environment for stuff like this, but for anyone that is interested in pursuing this, you could either:

* Create a new variant of Gemini (or any other framework that uses Resin) that is a copy of an existing variant except with the additional Resin install steps in the dockerfile.  At some later point after perf data has been collected in Citrine, use that to inform a decision about whether to change other frameworks.
* Simply try it out locally and tell us what you find.  If you see a consistent performance benefit from adding those install steps, that's good enough for me.

**Comment by michaelhixson** [comment]
Are you planning to do that experiment @zloster?  If not, mind if I reopen this issue to track our intent to do it?

**Comment by zloster** [comment]
@michaelhixson I'll not be able to do it in the coming couple of weeks.

**Comment by zloster** [comment]
The [latest results on Citrine](https://www.techempower.com/benchmarks/#section=test&runid=aa3d1cda-5cb6-489f-bd01-1e3718ca4d8e&hw=ph&test=json&p=zik0zb-zik0zj-zik0zj-zik0zj-v&f=35t1-5m9s-pa8-75-0-8vsmkg-0-2hwcg-0-0) are confirming my local results: `plaintext` has a lower throughput (on higher concurrencies) but `json` is performing better. The percent difference is not the same but this is expected. Compare `servlet` vs `servlet-lib-native`.

**Comment by michaelhixson** [comment]
The fact that it's not a performance increase across the board and [the bloat it adds](https://github.com/TechEmpower/FrameworkBenchmarks/blob/0d8e1f0d85d57a66c7d93860838722b16e0a43ea/frameworks/Java/servlet/servlet-lib-native.dockerfile#L11-L61) to the Dockerfile is unfortunate, but if that's what Resin recommends in their documentation, then that seems like a reasonable thing to do.

Also, the circumstances have changed since I initially removed the `configure` and `make` steps.  Back then we were trying to share one Resin base Dockerfile across all projects.  The Resin installation steps were essentially part of our toolset.  Now every framework is its own Docker island, so I'm content to leave the choice up to contributors.  We would accept a PR that makes this change in any Resin-using frameworks.

**Comment by zloster** [comment]
Given [the data here](https://github.com/TechEmpower/FrameworkBenchmarks/issues/4092#issuecomment-551295713) I object the part with `The fact that it's not a performance increase across the board`.
