### ISSUE TITLE
huge benchmark variation

### ISSUE THREAD

**Issue by Dmole** [TechEmpower/FrameworkBenchmarks#4218]
I was looking at the historic benchmark and noticed some unexpectedly large variations, making me doubt it's validity.

As an example I asked light-4j (2,435,150 down to 195,204)
https://github.com/networknt/light-4j/issues/315
and they think it's an environment change.
so what changed and is the variation reasonable due to said change?

**Comment by msmith-techempower** [comment]
Can you provide a couple of links to logging from:
1. Good runs
2. Bad runs

This will help us determine the dates involved and what may have changed during that span.

**Comment by Dmole** [comment]
The link in the OP mentions 15 and 17 as runs where the 2.4M to 0.2M drop was observed.

**Comment by nbrady-techempower** [comment]
The environment changed pretty significantly. Looking at the commits for light-4j it also seems that the test implementation was optimized for the round 15 environment. As the maintainer noted in the issue he closed, these benchmarks don't necessarily fit the business needs for light-4j. The test implementation could probably use some updating. If you're familiar with the framework, feel free to update! :)

**Comment by Dmole** [comment]
I have never used light-4j, but when a benchmark can drop a product from the top of the list to the bottom of the list without explanation or recognizing it as an issue, the benchmark can't be worth mutch. Ideally there would be a column for percent change from last run and are reason beside anything with a large change.

**Comment by nbrady-techempower** [comment]
@Dmole The explanation is fairly simple, as I've already explained: The environment changed significantly and this particular test implementation was specifically tuned to the older environment. Before we release rounds, we do a fairly broad check to make sure that major variations have explanations. You can read about the changes to the environment in the Round-specific blogs.

**Comment by Dmole** [comment]
Thank you for trying to help me understand,

Your confidence in environment change causing this variation is still not clear to me because the page 
http://www.techempower.com/benchmarks/#section=environment&hw=cl&test=plaintext
lists no change on the cloud enviroment from 15 to 16 and yet there is a large change in number (668k to 50k for light-4j)


http://www.techempower.com/blog/2018/06/06/framework-benchmarks-round-16/
said "...convert... test ... to ... Docker" and 
"Docker's overhead is immeasurably minute"

Either someone considers 10x as "minute" or I did not find any explanation for the example variation.

**Comment by msmith-techempower** [comment]
> http://www.techempower.com/blog/2018/06/06/framework-benchmarks-round-16/
said "...convert... test ... to ... Docker" and
"Docker's overhead is immeasurably minute"

> Either someone considers 10x as "minute" or I did not find any explanation for the example variation.

Blaming the switchover to Docker as the source for **one test implementation's** performance drop from one round to the round-after-next seems implausible.

Round15 was done on completely different hardware: different clock speeds, different core count, different network cards, different switch, etc than Round17. Comparing the two is an apples to oranges situation and flawed thinking.

On the whole, untouched frameworks which were **not** optimized for the hardware used in Round15 performed, on the whole, **better** in Round17 because of the improvement to the hardware. 

The drop in performance for a test implementation which **may be** optimized for the hardware used in Round15 is not unsurprising, but the magnitude of the drop is. I agree with @nbrady-techempower in his suggestion of auditing the implementation to ensure that:

1. core count used is correct
2. any run flag aimed at performance on r15's hardware be corrected

We **do** have an internal tool that alerts us to deltas from one run to the next, but it may not have been in place when the hardware change occurred and even if it was, the hardware change caused huge deltas for 99% of the test implementations for the reasons mentioned above.

We strive to try and maintain a fair playing field for the benchmarks we capture and publish, but in this case it seems like bad luck - there was a hardware swap that made all results look astonishingly different and the next subsequent run had `light-4j` as "still" performing poorly within our delta, so we were not alerted.

**Comment by Dmole** [comment]
I think you missed that I compared the cloud environment for which there was no "different hardware" from 15 to 16 yet a 10x performance drop for light-4j.

Removing the data point without understanding why the variation, would only encourage me to bring up the next example (assuming I did not stumble on the only outlier on my first look), so it's probably better to programmatically go through the history, highlight the outliers look into what caused them.

**Comment by msmith-techempower** [comment]
> I think you missed that I compared the cloud environment for which there was no "different hardware" from 15 to 16 yet a 10x performance drop for light-4j.

We also switched from AWS to Azure cloud instances at the same time, so there are indeed hardware differences. As with the physical hardware, most implementations improved in performance while `light-4j` deteriorated. So, my explanation still sounds like the most reasonable one.

**Comment by nbrady-techempower** [comment]
Did you look at the history of the test implementation between rounds? Did you happen to look at the test implementation code at all? It might be important to note that we don’t maintain those; we rely on the framework maintainers/contributors to submit and update those implementations. Like @msmith-techempower said, we have an internal tool that helps us validate a round’s results. So, yes, you probably came across one of the outliers. For the most part, the outliers are found by the maintainer of the implementation and they can provide context. To speak to the original issue, which to me read: “This one implementation varied too much between rounds so the entire benchmark is bunk” seems premature without any due diligence. We work both internally and with a variety of implementation maintainers to make sure results make sense. There will be outliers in the hundreds of tests. Normally environments don’t change as much as they did in those rounds, results can vary for other reasons like underlying dependency changes, core test implementation changes, etc.

**Comment by Dmole** [comment]
"We also switched from AWS to Azure cloud instances at the same time..."

Is that documented somewhere? (it's not on the 16 blog)

"Did you happen to look at the test implementation code at all?"

No; I thought I'd ask people familiar with the code. And if removing a data point is under consideration (or better yet a data/code review) maybe it was the right thing to do.

. I could look for other outliers, or for the maintainer of that particular example, or at the code, or if the results are environment dependent to such a degree maybe it's best to run them in the environments available to me...

**Comment by nbrady-techempower** [comment]
Gotcha. My point was simply we’re not the ones the most familiar with the code because we don’t write the implementations. We do check them as best we can to make sure they comply with our comprehensive test rules and even then sometimes it requires a little help and a community effort. I believe the Azure switch happened in Round 13 and that’s documented in the environment details.

Seems like light-4j probably started performing poorly due to a change in the implementation code. The results are repeated consistently in all environments now.

**Comment by nbrady-techempower** [comment]
Also, check out https://tfb-status.techempower.com

**Comment by Dmole** [comment]
So we agree the cloud environment did not change (other than docker) for cloud from r15 to r16, removing environment from the likely explanations for the 10x light-4j performance drop.

And there were no changes to the Plaintext test anywhere close to the 2018/02/14 - 2018/06/06 range;
https://github.com/TechEmpower/FrameworkBenchmarks/commits/master/frameworks/Java/light-java/src/main/java/com/networknt/techempower/handler/PlaintextGetHandler.java

So that leaves the code changes for docker unless anyone has any other ideas?
(the java change for docker seems most likely)

**Comment by nbrady-techempower** [comment]
@Dmole I don't understand why you keep skipping over test implementation changes?

**Comment by nbrady-techempower** [comment]
@stevehu Thanks! My guess is it may be related to setup changes. In the move to Docker, we also updated some core dependencies. I believe all Java frameworks were using Java 8 previously, and now most are pulling from a maven Java 10 base as an example.

**Comment by Dmole** [comment]
@nbrady-techempower now that stevehu [fixed](https://github.com/networknt/light-4j/issues/315#issuecomment-457833562) this issue (60 days after it was closed...), have you considered adding a "% variation from last round" column to make it easier to spot such regressions in the future?
