### ISSUE TITLE
Tfb-status Azure next run date?

### ISSUE THREAD

**Issue by vlazar** [TechEmpower/FrameworkBenchmarks#4281]
Not really an issue, but is there a way to know when the next run on Azure would be?

Citrine and Azure seem to require different DB pool settings for optimal performance.

So I'm waiting for results from Azure in addition to Citrine to continue optimizing DB pool settings for Crystal started in #4189 #4160

**Comment by michaelhixson** [comment]
> is there a way to know when the next run on Azure would be?

Short answer: no.

Currently, we only benchmark on Azure when we're intending to publish a new round, which is once or twice per year but not on any fixed schedule.  Assuming we continue like this, you may have to wait a long time for those results.  You maybe have better luck trying to optimize for your local development environment, perhaps tweaking the CPUs and memory available to Docker to be closer to the Azure D3v2 instance specs, assuming your hardware is more powerful than the D3v2.

Alternatively, we could benchmark on Azure more often.  We are not using all the Azure credits we have now.  If we do this, we'd want to figure out how to automate more of the process.  Each of the past few Azure runs has involved a few hours of human effort.

@msmith-techempower @nbrady-techempower @bhauer I'm curious if you guys have thoughts about benchmarking on Azure more often.

**Comment by msmith-techempower** [comment]
There are definitely thoughts on the matter, but we do not have the credits to do it continuously. We should discuss this at our next internal meeting and see what we come up with.

**Comment by nbrady-techempower** [comment]
I'm not as familiar with Azure as I am with AWS, but it would be great if we could essentially flip the switch on the machines that we've already provisioned, they start up and pull from the latest master, push to tfb-status, and shutdown until manually restarted.

I'm definitely all for it if we have the credits.

**Comment by vlazar** [comment]
Thanks for answers guys. For now I'm going to stop waiting for Azure and gather more data for Citrine. Any new data would be useful.

**Comment by bhauer** [comment]
I agree with @nbrady-techempower: it would be great if we could enhance the toolset to automate the full Azure routine (spin up the VMs, get things prepped, do a run, capture results, and then spin down the VMs).  If that was then on a monthly schedule, we would remain well within the Azure credit limits we've got.

But it's anyone's guess how much effort that would involve.

**Comment by msmith-techempower** [comment]
I want Brian’s suggestion so much.

**Comment by volyrique** [comment]
I have a somewhat related question - I set up my own Azure environment, but I got different results in many tests, even though I was using the same D3 v2 instances. The main difference I can think of right now is the virtual machine region - which one are you using? Is there any other setting that in your opinion might cause a significant variation in the results?

**Comment by nbrady-techempower** [comment]
@volyrique I’ll check for you on Monday. I’m not sure off the top of my head. You’re using a multi-machine setup?

**Comment by volyrique** [comment]
Yes, 3 + 1 control machine, which is actually D1 v2, but it shouldn't matter because it is just running the `tfb` script.

**Comment by nbrady-techempower** [comment]
Yeah that one shouldn’t matter. How different are your results? This issue comes up so often it would be good to know, if you have the exact same specs, what other things could be causing it.

**Comment by volyrique** [comment]
I rerun the `h2o` tests with the setup above (3 standard D3 v2 virtual machines and 1 standard D1 v2). All of them were in the UK South region, and were running Ubuntu Server 16.04 LTS. I checked out commit ecf99c9 in the repository to match the last continuous benchmarking run on Azure, [ca17a763-f7a3-4fc2-b5b3-f892ae897506](https://tfb-status.techempower.com/results/ca17a763-f7a3-4fc2-b5b3-f892ae897506). Here are the results:

| Test | My run | TFB run | Ratio |
| - | - | - | - |
| JSON serialization | 247276 | 170451 | 0.69 |
| Single query | 56189 | 38820 | 0.69 |
| Multiple queries | 2787 | 2104 | 0.75 |
| Fortunes | 52941 | 34843 | 0.66 |
| Data updates | 2073 | 1751 | 0.84 |
| Plaintext | 632405 | 712925 | 1.13 |
| Cached queries | 9084 | 8927 | 0.98 |

I have attached my [results.json](https://github.com/TechEmpower/FrameworkBenchmarks/files/3051642/results.zip) file for reference.

**Comment by nbrady-techempower** [comment]
Have you made any updates to h2o, or are there any dependencies that were updated, that would be reflected in your run but not ours? One thing you have to remember is that, even though you’re using the same commit hash and same Dockerfile, the Dockerfile may be pulling in newer versions or dependencies in later builds if your framework / dependencies aren’t tied down to specific commits / versions.

**Comment by volyrique** [comment]
I think it is safe to say that the [Dockerfile](https://github.com/TechEmpower/FrameworkBenchmarks/blob/ecf99c943b7a5464d15d252a60ae12485c978020/frameworks/C/h2o/h2o.dockerfile) has got the dependencies pretty much locked down.

The virtual machines (including the control one) were brand new ones - after bringing them up I just ran the following commands:
```
sudo apt install docker.io
sudo usermod -aG docker $USER
sudo apt update
sudo apt upgrade
```
and also the [manual deployment setup steps](https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Benchmarking-Getting-Started#manual-deployment) from the Wiki before rebooting the machines.

Then on the control machine I cloned the repository, checked out the proper revision, and ran the Docker command from the Wiki page above (of course, I adjusted the IP addresses, and added `--test h2o`, so that I don't run everything).

One thing that I forgot to mention is that when setting up the virtual machines, I mostly used the default settings (well, I had to enable SSH, etc.), which included accelerated networking.

**Comment by nbrady-techempower** [comment]
Ok. I think we provisioned the machines for Azure with a terraform script so I’ll try and get you access to those early this week and you should be able to duplicate the exact infrastructure. Afaik we didn’t enable anything outside of the default setup. I would bet the key difference here is the region. If you have the credits and don’t mind could you add US-west to your chart above.

**Comment by volyrique** [comment]
Just checking - is that West US or West US 2?

**Comment by nbrady-techempower** [comment]
To be honest, I’m not sure. I’ll check when I get into the office tomorrow.

**Comment by nbrady-techempower** [comment]
@volyrique Turns out we're using `Central US`

**Comment by volyrique** [comment]
Unfortunately, the results I got when running in the Central US region were quite similar to what I measured before:

| Test | UK South | Central US | TFB run |
| - | - | - | - |
| JSON serialization | 247276 | 243542 | 170451 |
| Single query | 56189 | 57349 | 38820 |
| Multiple queries | 2787 | 2785 | 2104 |
| Fortunes | 52941 | 52201 | 34843 |
| Data updates | 2073 | 2142 | 1751 |
| Plaintext | 632405 | 673801 | 712925 |
| Cached queries | 9084 | 9053 | 8927 |

I have attached the [results.json](https://github.com/TechEmpower/FrameworkBenchmarks/files/3058579/results.zip) from the run in the Central US region as well.

**Comment by nbrady-techempower** [comment]
Here are the terraform scripts we used to set up and deploy the benchmarks. Maybe you'll see something here that's different: https://github.com/jsongte/tfb-azure-terraform/tree/azure-terraform-setups

**Comment by michaelhixson** [comment]
> One thing that I forgot to mention is that when setting up the virtual machines, I mostly used the default settings (well, I had to enable SSH, etc.), which included accelerated networking.

This jumped out at me because IIRC accelerated networking was not the default when I was managing our Azure environment for the past few rounds.  Something we were using (the OS version?) did not support accelerated networking out of the box at the time, so we didn't use it.

If I'm reading Terraform's documentation and our scripts correctly, accelerated networking wasn't enabled for this more recent Azure run either, since the setting defaults to `false` in Terraform and we didn't override it in our script.

https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#enable_accelerated_networking

https://github.com/jsongte/tfb-azure-terraform/blob/f88cec19a3a8c2f6a4f1858b67af5ccb3b0e5864/terraform/tfb-app.tf#L27-L40

**Comment by volyrique** [comment]
So, are you going to use accelerated networking for the Azure runs in the future?

**Comment by michaelhixson** [comment]
I think we should, especially if it's as easy as adding `enable_accelerated_networking = true` to that script.

Maybe a reasonable way forward from here is: we make that change in our script, and whenever we do the next run, we check if h2o's results are closer to your results.  Not sure when the next run will be.  I think we're waiting for our Azure credits to regenerate.

**Comment by nbrady-techempower** [comment]
Yeah I think we should get these terraform scripts in to our main repo `deployment/azure` once they're complete so you can easily reproduce.

**Comment by michaelhixson** [comment]
I created #4636 for enabling accelerated networking.

**Comment by zloster** [comment]
@volyrique @michaelhixson @nbrady-techempower 
There was improvement in the Linux kernel about the TCP listener. The change is [released with kernel 4.4](https://kernelnewbies.org/Linux_4.4#TCP_listener_handling_completely_lockless.2C_making_TCP_servers_faster_and_more_scalable).
In Ubuntu 14.04 this kernel is installable after [14.04.5](https://wiki.ubuntu.com/Kernel/Support#A14.04.x_Ubuntu_Kernel_Support). It's not automatic upgrade (as far as I remember).

Maybe this change is also at play here?

**Comment by nbrady-techempower** [comment]
@zloster Our base azure image is 16.04 latest which should be on 4.4.* https://github.com/jsongte/tfb-azure-terraform/blob/f88cec19a3a8c2f6a4f1858b67af5ccb3b0e5864/terraform/tfb-app.tf#L52

**Comment by volyrique** [comment]
I found another difference between the Terraform scripts and the Azure portal defaults - the [OS disk type](https://github.com/jsongte/tfb-azure-terraform/blob/f88cec19a3a8c2f6a4f1858b67af5ccb3b0e5864/terraform/tfb-app.tf#L59) is "Standard HDD" instead of "Standard SSD". I am not sure how much of a difference it makes.

For the sake of completeness, here are my results from the Central US region with accelerated networking disabled and without SSDs:

Test|My run|TFB run|Ratio
-|-|-|-
JSON serialization|172861|170451|98.61%
Single query|49907|38820|77.78%
Multiple queries|2568|2104|81.93%
Fortunes|42733|34843|81.54%
Data updates|1929|1751|90.77%
Plaintext|871379|712925|81.82%
Cached queries|11286|8927|79.10%

The JSON serialization results are more or less the same as the continuous benchmarking run. As for the rest - maybe I just got lucky, and didn't share the physical hardware with any other Azure user?

As usual, I have attached the [results.json](https://github.com/TechEmpower/FrameworkBenchmarks/files/3064174/results.zip) file for reference.
