### ISSUE TITLE
Payload size performance benchmarks

### ISSUE THREAD

**Issue by jobs-git** [TechEmpower/FrameworkBenchmarks#4375]
For typical web applications, pure text payloads may reach more or less 1MB. So it must be appropriate that this may become part of realistic setup scenario.

Right now, its seems there is no test yet that measures performance of frameworks on larger payloads. Typically, an efficiency performing framework should communicate the payload to the network through DMA (Direct Memory Access), so that the payload size would only affect the network bandwidth and has minimal effect on cpu utilization.

**Comment by bhauer** [comment]
See issue #133 for a summary of additional/future test types that we have documented for consideration.  You are welcome to add your thoughts on that issue!  To date, additional test types have been very time-consuming to adopt, but we will continue to make efforts there.

Presently, without better definition, we would likely prioritize a large-payload test type lower because it's relatively easy to saturate the available network bandwidth with a large static or trivial dynamic response.  However, a large payload test-type that includes a sufficiently complex algorithmic or data-processing workload would be promising.  Ultimately, with sufficient time, I wouldn't be opposed to including even a static or trivial dynamic large payload test-type.  Additional data is almost always a good thing.  But priorities-wise, I feel other candidate test-types would yield more interesting results data.

**Comment by jobs-git** [comment]
Hi, its already in 15 & 19. Thank you
