### ISSUE TITLE
Laravel-Swoole: Error 1004: swFactoryProcess_finish: send 1494 byte failed, because connection[fd=10064] is closed.

### ISSUE THREAD

**Issue by oozone** [TechEmpower/FrameworkBenchmarks#4513]
What did you do? If possible, provide a simple script for reproducing the error.
Doing benchmarks from Web Framework Benchmarks (Laravel, Cakephp, Laravel-swoole). The first two work flawlessly but the swoole version gives 1004 errors.
git clone from https://github.com/TechEmpower/FrameworkBenchmarks
make sure docker is installed
run command in main folder: ./tfb --test laravel-swoole

What did you expect to see?
No errors, no connections closed.

What did you see instead?
Connections closed and thus failure of the request, see attached pic.

What version of Swoole are you using (show your php --ri swoole)?
SWOOLE_VERSION=4.2.1

What is your machine environment used (including version of kernel & php & gcc) ?
Debian
Kernel: 3.14.32-xxxx-grs-ipv6-64
PHP: PHP 7.2.15-1+020190209065123.16+stretch1.gbp3ad8c0 (cli) (built: Feb 9 2019 06:51:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.15-1+020190209065123.16+stretch1.gbp3ad8c0, Copyright (c) 1999-2018, by Zend Technologies

gcc: gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

![laravel-swoole](https://user-images.githubusercontent.com/4332841/53861796-797ff380-3fe5-11e9-97dc-f78df6fd5e68.png)

**Comment by nbrady-techempower** [comment]
ping @bfinlay

**Comment by bfinlay** [comment]
I agree with the submitter that these messages from Swoole indicate socket timeouts.

The reason no errors are seen is because in the Techempower benchmark methodology, timeouts are counted separately from errors.   To be considered an error, the service has to return a non-200 or non-300 error response.  If no response is received within 8 seconds, it is considered a timeout. 

This seems like a reasonable approach because when doing load testing, timeouts are expected.  That's how you know you have reached max load.

The reason for the difference in messages is because of the different technology stack.   The technology stack for an incoming request in the standard PHP "Laravel" test is NGINX->PHP-FPM->Laravel.   The technology stack for the "Laravel-swoole" test is Swoole->Laravel.   Swoole replaces NGINX and FPM-PHP, and it displays different error messages for timeouts than NGINX PHP-FPM do (which is apparently nothing as configured in the test.)  If you run other tests like "vertx-postgres" you will see similar error messages.

The PHP "Laravel" test is not actually "flawless" (if flawless means running without socket timeouts).  Both the PHP "Laravel" test and the "Laravel-swoole" test have socket timeouts.  You can see the timeouts by opening the "results.json" file and searching for "timeout".   Tests with timeouts have a timeout field.  

For example, this is an excerpt from the "laravel" results.json running on my machine.   You can see timeouts of 330, 119, and 190
```
"plaintext": {
      "laravel": [
        {
          "latencyAvg": "917.90ms", 
          "latencyMax": "3.96s", 
          "latencyStdev": "570.34ms", 
          "totalRequests": 40953, 
          "startTime": 1551911828, 
          "endTime": 1551911843
        }, 
        {
          "latencyAvg": "3.96s", 
          "timeout": 330, 
          "latencyMax": "8.00s", 
          "latencyStdev": "2.28s", 
          "totalRequests": 38830, 
          "write": 0, 
          "read": 0, 
          "connect": 0, 
          "startTime": 1551911845, 
          "endTime": 1551911860
        }, 
        {
          "latencyAvg": "2.66s", 
          "timeout": 119, 
          "latencyMax": "7.96s", 
          "latencyStdev": "1.58s", 
          "totalRequests": 39423, 
          "write": 0, 
          "read": 0, 
          "connect": 0, 
          "startTime": 1551911862, 
          "endTime": 1551911878
        }, 
        {
          "latencyAvg": "2.64s", 
          "timeout": 190, 
          "latencyMax": "7.96s", 
          "latencyStdev": "2.26s", 
          "totalRequests": 31028, 
          "write": 0, 
          "read": 0, 
          "connect": 0, 
          "startTime": 1551911880, 
          "endTime": 1551911895
        }
      ]
    }, 
```   

Screenshot of "laravel" test run also indicating timeouts.  For the 'plaintext' tests, TFB shows the timeouts in the output.
![2019-03-06_16-56-15](https://user-images.githubusercontent.com/1757856/53920445-cfc75380-4032-11e9-9c29-d2c39bd55630.png)


"laravel-swoole" also indicates timeouts.   This excerpt shows timeouts of 14, 64, and 81 below.
```
"json": {
      "laravel-swoole": [
        {
          "latencyAvg": "3.07ms", 
          "timeout": 14, 
          "latencyMax": "99.99ms", 
          "latencyStdev": "5.69ms", 
          "totalRequests": 104086, 
          "write": 0, 
          "read": 0, 
          "connect": 0, 
          "startTime": 1551906748, 
          "endTime": 1551906763
        }, 
        {
          "latencyAvg": "5.49ms", 
          "latencyMax": "120.62ms", 
          "latencyStdev": "6.99ms", 
          "totalRequests": 105585, 
          "startTime": 1551906765, 
          "endTime": 1551906780
        }, 
        {
          "latencyAvg": "9.85ms", 
          "timeout": 64, 
          "latencyMax": "123.94ms", 
          "latencyStdev": "7.30ms", 
          "totalRequests": 104825, 
          "write": 0, 
          "read": 0, 
          "connect": 0, 
          "startTime": 1551906782, 
          "endTime": 1551906797
        }, 
        {
          "latencyAvg": "18.54ms", 
          "latencyMax": "166.60ms", 
          "latencyStdev": "12.67ms", 
          "totalRequests": 109355, 
          "startTime": 1551906799, 
          "endTime": 1551906815
        }, 
        {
          "latencyAvg": "34.98ms", 
          "timeout": 81, 
          "latencyMax": "237.41ms", 
          "latencyStdev": "20.43ms", 
          "totalRequests": 112632, 
          "write": 0, 
          "read": 0, 
          "connect": 0, 
          "startTime": 1551906817, 
          "endTime": 1551906832
        }, 
        {
          "latencyAvg": "73.04ms", 
          "latencyMax": "284.70ms", 
          "latencyStdev": "37.63ms", 
          "totalRequests": 106061, 
          "startTime": 1551906834, 
          "endTime": 1551906849
        }
      ]
    }, 
```

I don't have a corresponding screenshot for "laravel-swoole" because the "json" test doesn't show timeouts in the console output, apparently only the "plaintext" test does.  And the "laravel-swoole" test has no timeouts for the "plaintext" test, at least on my machine.

**Comment by bfinlay** [comment]
Pull request #4525 updates to Swoole 4.3.0 and laravel-swoole 2.6.5.3 which improves the plaintext results.
