### ISSUE TITLE
Update rust dependencies

### ISSUE THREAD

**Issue by JuanPotato** [TechEmpower/FrameworkBenchmarks#4551]
Hi, I noticed the rust commit that updated the rust version for all the rust programs (which is out of date now), and was wondering if the dependencies were out of date.

I noticed a few core dependencies of some of the programs have updated their major version (0.5 -> 0.6) and the rust dependencies in Cargo.toml still reference the old version.

Some main examples are 
 * Iron 0.5 -> 0.6
 * Nickel 0.10 -> 0.11
 * Hyper 0.10 -> 0.12
 * rouille 1.0 -> 3.0
 * thruster 0.5 -> 0.6

I couldn't find anything in the rules about using the latest version of your core library, but I thought it would make sense to update them. I would try to update things but I'm not sure what I need to do to make sure everything still works.

**Comment by nbrady-techempower** [comment]
@JuanPotato You can update them and open up a PR and our continuous integration will run the tests in the PR or you can follow the instructions on the [wiki](https://github.com/TechEmpower/FrameworkBenchmarks/wiki) for setting up your own environment and testing. We don't consider updating the latest version of libraries an issue, especially since we would have too many to track ourselves. We let the community update those as needed. So feel free to take a shot at it and if you run into any trouble we'll be happy to help you in a PR.
