### ISSUE TITLE
libreactor json benchmark

### ISSUE THREAD

**Issue by fafhrd91** [TechEmpower/FrameworkBenchmarks#4788]
[libreactor](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/libreactor/src/main.c#L65) uses [libclo](https://github.com/fredrikwidlund/libclo/) library for json serialization 
readme states `It does this by constructing the JSON structures as compound literals, which does not require any runtime memory allocation or system calls.`
that sounds like violation of rules

**Comment by zloster** [comment]
@fafhrd91 
The rules define only that before serialisation there should be a memory allocation for the data structure that will be serialised. They do not imply restrictions of how the JSON serialisation should be achieved.

`libreactor` is calling [this macro](https://github.com/fredrikwidlund/libclo/blob/555dd56fd537effd4e8d7713b7cf66ab284d7329/src/clo.h#L9) which seems to be allocating a `C struct`. This `struct` is sent for serialisation immediately after creation. That's my understanding of the code.

Could you add a little bit more explanation why you think there is a violation of the rules.

**Comment by fafhrd91** [comment]
It is about ‘literal’ in lib description. It may avoid actual json serialization, but I don’t know c to be sure

**Comment by zloster** [comment]
Here is my interpretation of the code. IMO it seems OK - there is escaping for the special symbols and handling of the UTF-8 encoding.

The framework is calling this method:
https://github.com/fredrikwidlund/libclo/blob/555dd56fd537effd4e8d7713b7cf66ab284d7329/src/clo.c#L184

Later the code will move through this portion:
https://github.com/fredrikwidlund/libclo/blob/555dd56fd537effd4e8d7713b7cf66ab284d7329/src/clo.c#L130-L147
The case is `CLO_OBJECT` (check the defined macro).

- First start with writing the "{" in a buffer;
- Mark that this is the first field (`first=1`);
- Cycle over key-value pairs (`clo_pair`)
- (inside the `for` loop) - some logic about the `first` variable;
- Call for `key` string encoding. The code seems to the necessary activities - some escaping and such:
https://github.com/fredrikwidlund/libclo/blob/555dd56fd537effd4e8d7713b7cf66ab284d7329/src/clo.c#L91-L122
- Write `:` to the buffer;
- Recursion call with the `value` data;
- Write the closing `}` in the buffer.

Again, this is my interpretation. Let's see what will say someone with better knowledge of `C`.

**Comment by volyrique** [comment]
You should have pinged @fredrikwidlund.

> readme states `It does this by constructing the JSON structures as compound literals, which does not require any runtime memory allocation or system calls.`
> that sounds like violation of rules

IMHO it just means that there is no call to `malloc()` (or something similar), not that there isn't any memory allocation at all - it will result in a stack allocation, which is the fastest type of memory allocation, hence the preference.

The only subtlety is that if link-time optimizations are applied during the build process, and the compiler has visibility into both the `clo_encode()` and `json()` functions, it can inline the former into the latter, and evaluate a lot statically (and also remove the allocation by propagating the structure member values to the places they are used, since they are constant). However, there is no reason why the same thing couldn't happen in other implementations, in particular the ones that are subject to JIT compilation (in which case the compiler usually has a lot of visibility into libraries and runtime behaviour). The only implementation that would be at a clear disadvantage would be a hypothetical (at this point) assembly language implementation because obviously it wouldn't be subject to compiler optimizations. Anyway, as far as I can tell, from the point of view of the C language semantics, the code does what the rules require.

**Comment by fredrikwidlund** [comment]
libclo does runtime serialisation to an output buffer on the heap before flushing it to the socket. The output buffer is typically reused during an http session, and avoids in most cases the need to allocate further memory. 

Compound literals inside functions are allocated on the fly, on the stack, like local variables. They are indeed runtime constructions, they can contain non constant expressions, etc.

I do suspect that in a lot of other implementations these seemingly constant expressions are serialised once and then reused in different ways. An improvement to the benchmark would be to add a non constant expression in the JSON reply to avoid this.

**Comment by nbrady-techempower** [comment]
I think we can consider this closed now. I agree with your last statement @fredrikwidlund but don't see that happening any time soon. We have found and fixed a few implementations that would have taken advantage of that, but if anyone spots others we'd be happy to help fix.
