### ISSUE TITLE
Test requirements out of sync between wiki and results website

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/FrameworkBenchmarks#5015]
These two pages should show the same set of requirements, but they don't:
* https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview
* https://www.techempower.com/benchmarks/#section=code

Differences that I noticed:
* The wiki has 3 general requirements, the results website has 7 general requirements.
* The wiki has an outdated version of Multiple Database Queries rule 6, which explains how rows must be selected individually.
* The wiki has a sentence related to redis in Single Database Query rule 6 that the results website doesn't have.
* The results website says that specifying the character encoding of application/json is unnecessary in Multiple Database Queries rule 9, the wiki doesn't.  **Edit:** I had this backwards at first.
* The wiki has rules for the Caching test, the results website doesn't.

**Comment by bhauer** [comment]
For each of these, let's decide which should take precedence.  My thoughts:

1. General requirements: Results web site is more accurate.
2. Multiple query rule 6: As you said, the results web site is more recent.
3. Single query rule 3: Looks like the wiki is better here since it mentions Redis at all.
4. Multi query rule 9: Which do we prefer?  I don't have a strong preference, but I think it feels more correct to include the MIME type.
5. Caching test: I am fine with leaving this only on the wiki until the results web site is changed to include the Caching test results.

**Comment by michaelhixson** [comment]
I had item 4 backwards.  The results website includes this sentence and the wiki does not

> Note that specifying the character encoding is [unnecessary for this content type](https://www.ietf.org/rfc/rfc7159.txt).

I think the results website's content is better here and that we should add this sentence to the wiki.  Note that the same sentence appears under multiple test types.

For the other items, I agree with Brian.

Process-wise, I wish we either didn't have two copies of the rules or somehow ensured that we always edited them in tandem.  For this task though, I guess it's sufficient to do a one-time sync.

**Comment by nbrady-techempower** [comment]
I agree with not having two copies. @bhauer what do you think of just linking to wiki sections once they're updated?

**Comment by bhauer** [comment]
That sounds great.  I can change the results web site to link directly to the Wiki whenever.  Just let me know when you're done with the changes.

**Comment by nbrady-techempower** [comment]
Wiki is updated

**Comment by bhauer** [comment]
The results web site now links to the Wiki here on GitHub.
