### ISSUE TITLE
Toughts about Excluding/Removing Plaintext test (HTTP1.1 Pipelining) from Composite scoring

### ISSUE THREAD

**Issue by zloster** [TechEmpower/FrameworkBenchmarks#5259]
I'm talking about this page: https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Composite-Scoring-For-Frameworks

My main argument is:
The usage of the `HTTP 1.1 pipelining` is basically inapplicable to the current deployments.

More detailed:
The clients (web browsers) turned it off a long time ago. `curl` - [this year](https://daniel.haxx.se/blog/2019/04/06/curl-says-bye-bye-to-pipelining/). Most of the widely used reverse proxies doesn't implement it (`HAproxy`, `Varnish`, `NGINX`). Exposing single/couple of WEB application servers directly to the Internet in 2019? I'm not sure only for the case `microservices communication`: but usually `HTTP` is thrown out and some other `RPC` protocol is deployed.

There are also some interesting security implications: https://medium.com/@knownsec404team/protocol-layer-attack-http-request-smuggling-cc654535b6f

And finally there is the [`HTTP/2` with multiplexing](https://wiki.developer.mozilla.org/en-US/docs/Web/HTTP/Connection_management_in_HTTP_1.x#HTTP_pipelining).

**Comment by bhauer** [comment]
Thanks for the input, @zloster.

I'd like to get further input from others.  I am not sure Plaintext should be removed outright, but perhaps my bias adjustment (0.75) should be even more significant (e.g., 0.5 or even lower) to further diminish the value of the Plaintext test in the composite score.

As a sidebar discussion, we really should get moving on HTTP/2 pipelined tests as mentioned in #133.

**Comment by sebastienros** [comment]
In the ASP.NET team we currently have a task to suggest adding an HTTP/2 scenario. We started talking about it a few weeks ago as this is a prerequisite for GRPC. That would also somehow help with the fact that there isn't any https scenario either. Someone in the team will file an issue with some initial thoughts about what this scenario could be (streams, connections, ...).

**Comment by zloster** [comment]
I'm closing this as it is more than 6 (six) months old and the only additional input is from the Microsoft team with irrelevant writing. There are well known issues where new use-cases/tests could be suggested and so on.

So to summarise my view:
The HTTP 1.1 pipe-lining is not usable in a "realistic" deployment scenario (see my first comment). Also the characteristics of the "workload" are absurd for "realistic measurement" - workloads without memory allocations aren't that many:
1) piping to `/dev/null`;
2) NTP serving of something similar.

Then this:
https://github.com/TechEmpower/FrameworkBenchmarks/issues/4092#issuecomment-614772349 - 
> make our benchmarking environment less realistic.

So I see a big discrepancy between the "claimed goal" and the real actions (including an extremely unrealistic test in the Composite score) of the team but almost nobody shares this view.

**Comment by bhauer** [comment]
The Plaintext test type was and is still intended as a very minimal exercise of HTTP request routing and header processing within web application platforms and frameworks.  It was expressly designed to minimize memory pressure on the environment by not requiring the instantiation of new objects with the application space.

It is now quite old, having been introduced many years ago.  Ideally it would be superseded or augmented with an HTTP/2 test type of the same basic flavor.  Such a test would retain the intended ability to stress-test request routing by using an analog of pipelining, but would no longer do so using a largely unsupported protocol.  I'd like us to make progress toward getting that done, but it hasn't happened yet.

Until that is done, in my opinion, the Plaintext test type remains a viable measure of the request routing fundamentals of a framework.  I agree that it is, by far, the least realistic of our test types.  For that reason, although its base weighting for composite scoring is already low, I am agreeable to lowering is base weighting further.

The composite scoring base weights I am using are:

* **json** = 1.0
* **single-query** = 0.75
* **20-query** = 0.75
* **fortunes** = 1.5
* **updates** = 1.25
* **plaintext** = 0.75

Single-query and 20-query are reduced in weight because they are so similar.  The pairing of those two has a net weight of 1.5.  Fortunes is given extra weight because it's the most realistic.  Updates is given a bit of extra weight because it's the only test that exercises writing.  And Plaintext is reduced in weight because it's the least realistic test.

Overall, we have received little feedback about the composite scores feature, both after proposing it here and after launching Round 19.

As I said earlier, I am open to reducing the base weighting for Plaintext even further.  As you point out, there's not much counter opinion here, so unless someone speaks up, I will drop it to 0.5 for Round 20.
