### ISSUE TITLE
Policy against gaming the benchmarks?

### ISSUE THREAD

**Issue by mytskine** [TechEmpower/FrameworkBenchmarks#5550]
I've been reading the source code of some submitted applications, in order to learn more about optimization. I've seen an implementation that was clearly not respecting the rules. It declares a *realistic* approach, but the source code is nothing like the code of the demo application for this framework. The templating system is disabled and replaced by a raw process. The serialized output does not use the framework's way of producing JSON. The application calls many undocumented functions of the framework. Of course the goal is the public promotion the framework, with snapshots claiming these *independent benchmarks* prove its excellent performance.

I'm uneasy about this. On one side, I can't stand the benchmarks being deceptive and unfair. On the other side, I'm afraid this will be a contentious issue. And if this is not the only case, the only solution I can think of is introducing peer reviews that can re-qualify a submission as a *stripped* approach. But finding several peers for each domain will be hard. And minor languages and new frameworks will still get less scrutiny.

How does TechEmpower verify that an implementation is fair in its declarations?

**Comment by nbrady-techempower** [comment]
All you can do is post the framework here, we ping the maintainer, and we have a public discussion about it. We do our best to verify everyone is following the general rules, but it would be nearly impossible for us to learn the best practices or which components of a framework are undocumented.

Because this is a public repo, and the benchmarks are often used in the way you described, I think it's fair to open another issue calling out the parts that you think should classify it as stripped. All we ask is that you be respectful in your approach. Thanks!

**Comment by jcheron** [comment]
There are a number of things bothering me about this issue:

#### in form:
Opening an issue to publicly accuse certain authors of breaking the rules is not correct.

Not quoting the framework(s) concerned does not change the scope of the gesture and introduces a general suspicion that is totally useless.

It is much simpler and more constructive to question the authors about the lines they have committed. This opens a healthier and more constructive discussion, and helps to understand certain choices.

#### in substance:
You declare to have examined the code of this framework to learn more about its optimization. I deduce, perhaps wrongly, that you didn't know it initially.

And yet, in the meantime, you turn into a peer  (like the ones you ask for in this issue)  by declaring that the code implemented on Techempower does not respect the principles of the framework!

How do you know that the framework in question would not recommend in this context the use of native JSON encoding rather than the one proposed and that it would not encourage its users to disable certain features?

The fact that the _demo application_ is implemented in a different way does not seem to me to be a good assessment criterion. Each test on Techempower corresponds to certain implementation objectives. Deactivating certain functionalities considered useless seems to me to be a good practice within the framework of benchmarks (also in production). It is besides what you did partly for YII. 

Concerning the use of undocumented features, it's the same thing. This does not prove that the test is not realistically implemented, but rather that the framework documentation is incomplete. This is just unfortunate for its users and the development of its community...

Personally, I have worked on the code of some frameworks implemented here, in different languages, to contribute to their optimization, or simply to make them pass the tests.
This did not give me the necessary skills to appreciate this criterion distinguishing realistic or stripped tests, and even less the right to denounce possible non respect of the rules.

**Comment by pickfire** [comment]
Is this considered gaming the benchmarks? I was curious looking at how `pico.v` code was written and why was it faster than others by 5% for plaintext.
https://github.com/TechEmpower/FrameworkBenchmarks/blob/cfaad5b6418e23799bf7d62ba7e2536be53a6d62/frameworks/V/pico.v/main.v#L23-L32

This optimization looks interesting to me such that it only checks the prefix for the path.

**Comment by nbrady-techempower** [comment]
@jcheron This is the part that's important to me:

> All we ask is that you be respectful in your approach

I don't want anyone accusing anyone of doing anything. But if there are questions about an implementation, it will always be ok to open an issue about it. We're not going to change that. To your point about not knowing, I agree. I'd rather some research be done and even issues opened in that framework's repo if you have questions about the internals of a specific framework. I don't want to manage that here.

@pickfire No. The rules specify the "recommended" paths. If you built an app that had those endpoints, 🤷‍♂ 

Going to close this for now.
