### ISSUE TITLE
The number of sql connections used by a framework has a huge impact on its ranking.

### ISSUE THREAD

**Issue by matt-42** [TechEmpower/FrameworkBenchmarks#5662]
Hi all,

Did you notice that the number of sql connections used by a framework has a huge impact on its performances ?

Some frameworks are using the optimal number, some are not. This brings a huge bias in the ranking of the framework:
I was able to bring lithium from rank #40 to rank #2 on the update test by just lowering the number of sql connections, and all
sql tests are impacted.

To avoid this bias and to actually rank frameworks according to their performances, I propose that we constraint all frameworks
to use the same number of connections. What do you think ?

**Comment by nbrady-techempower** [comment]
I think this is one of those things we want to leave variable; what's best for yours may not be best for another but at the same time, if someone sees it works for you, and it works for them, they'll update.

With that said, feel free to update frameworks to use the same number of connections if you feel it will improve their results. Some maintainers are already trying a number of different configurations.

**Comment by volyrique** [comment]
Yes, the database updates test has been a nasty one for `h2o` because the optimal setting for it is less than ideal for the rest of the tests (I have documented my observations [here](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/C/h2o/README.md#performance-tuning)). And yes, I have determined the current number of database connections by meticulously trying all values in a reasonable range - the continuous benchmarking setup has been immensely helpful in that respect. Right after round 19 is finished would be the perfect time to do that for any test implementations that haven't gone through the same exercise.
