### ISSUE TITLE
Why let mysql execute more update statements than postgreSQL?

### ISSUE THREAD

**Issue by lizhichao** [TechEmpower/FrameworkBenchmarks#5983]
found that PostgreSQL requires 10752 expected, but why does it require 20480 expected for Mysql ?
in verification `updates/20` 
https://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/722209086

**Comment by jcheron** [comment]
The difference is not related to the database (Mysql, PostGre or Mongo), but to the possible usage of BulkUpdates.

The test performs a burst of Http requests, at a concurrency level of 512, on the url  `update/20` (20 objects to load).

In case of loading and updating each object at each Http request, the number of expected db queres is :
```
512 * (20 loadings + 20 updates) => 20480
```
In case of Bulk updates, only 1 db update query is performed for each Http request:
```
512 * (20 loadings + 1 update) => 10752
```

**Comment by lizhichao** [comment]
In mysql can use `replace into` to bulk updates

**Comment by jcheron** [comment]
In theory, with Mysql, you can use an `UPDATE` with `CASE/WHEN/THEN ELSE`:
```sql
UPDATE World SET randomNumber=(CASE WHEN id=? THEN ?
WHEN id=? THEN ?
...
ELSE id
END)
WHERE id IN (?, ?, ...)
```
or the `INSERT INTO` combined with `DUPLICATE KEY UPDATE`:
```sql
INSERT INTO World (id,randomNumber)
VALUES (?, ?), (?, ?),...
ON DUPLICATE KEY UPDATE
id = VALUES(id),
randomNumber = VALUES(randomNumber)
```

In practice it works, but not with this concurency level. In any case nobody has succeeded (with c=512).

Otherwise you can fall back and try the execution of updates in a transaction.

**Comment by lizhichao** [comment]
in a transaction execute 
```sql
REPLACE INTO World (id,randomNumber)
VALUES (?, ?), (?, ?)
```
can bulk updates.
This only needs to be executed once instead of 20 times

**Comment by jcheron** [comment]
I believe that the `REPLACE INTO` is still much more expensive than the 2 methods I mentioned before, since it will make a deletion and then an insertion for each row (you risk even more deadlocks!).

For the transactions, they are only useful if you have several instructions to execute, not in the case of BULK updates, where you only have one.

**Comment by lizhichao** [comment]
Added transactions will not have deadlock。You can test it

**Comment by jcheron** [comment]
It is the use of the `REPLACE INTO` in a Bulk update that I find costly.

For transactions, I don't see the point if you do a single SQL query in a BULK. 

The best is to try...
What I say is not word of gospel.

**Comment by lizhichao** [comment]
this is use `replace into` of ci result https://travis-ci.org/github/TechEmpower/FrameworkBenchmarks/jobs/722209086

**Comment by jcheron** [comment]
The verification procedure only counts updates, not delete+insert.
https://github.com/TechEmpower/FrameworkBenchmarks/blob/b88cfcbfe24445804abe5f3754bfa1582401412d/toolset/databases/mysql/mysql.py#L65-L68

That's why your queries are not counted.
As they are not counted, you can't know if you have missing queries or not...

From a performance point of view, I think it's a bad choice to use the `REPLACE INTO`, which is anyway more expensive than a single `UPDATE`.

**Comment by jcheron** [comment]
It would be necessary to check how the `PERFORMANCE_SCHEMA.SESSION_STATUS` table evolves when you perform `REPLACE INTO` queries...
The statistics are strange, though.
