### ISSUE TITLE
New frameworks not showing in the "composite" tab

### ISSUE THREAD

**Issue by bdw429s** [TechEmpower/FrameworkBenchmarks#6466]
I'm really not sure if this is a bug or not, but I haven't received any replies in 2 weeks when I tried to have a discussion about it here https://github.com/TechEmpower/FrameworkBenchmarks/discussions/6421 so I'm moving it to the issue tracker with hopes of getting feedback.

--------------------

I've added some new frameworks recently including
* `cfml`
* `cfml-adobe`

The comments on the ["composite" tab](https://www.techempower.com/benchmarks/#section=test&runid=8bfdbe5b-a7ce-4ec0-a788-c447e43382de&hw=ph&test=composite&a=2) say 

> Only frameworks that implement all test types are included. 

but all of my new frameworks implement all 7 tests and you can see their results on the other test tabs.  Yet, none of my frameworks show up on the composite tab.  Is there another requirement for my new framework to show up on this tab?

**Comment by nbrady-techempower** [comment]
This is likely because your frameworks haven't participated in an official round yet. Our (soon to be legacy) system hardcodes all the framework names that have participated in official rounds and we use those keys to do some lookups. We addressed most of those issues when we fixed the visualizations for new frameworks in between rounds, but looks like we missed this one. I'll see about getting that updated.

**Comment by bhauer** [comment]
The composite scores don't (currently) work for implementations that set the `Framework` attribute in *benchmark_config.json* to `None`.

When computing composite scores, I use the `Framework` attribute to find the peak performance for a given framework across multiple implementation permutations.  For each test type, the peak performance across all of of a framework's permutations is used for that test type's contribution to the composite score.  For example, a MySQL permutation may be peak for single-query and a Postgres permutation may be peak for fortunes.

In order to see *cfml* in the composite results, you could set its `Framework` attribute to `cfml`.  Once committed, this change would flow out on the next continuous run and then should show up.

**Comment by bdw429s** [comment]
Thanks for the input, guys.  I've submitted this pull here with the changes suggested.

https://github.com/TechEmpower/FrameworkBenchmarks/pull/6483

**Comment by bhauer** [comment]
Excellent. Let me know if that doesn't help resolve the issue once a continuous run completes.
