### ISSUE TITLE
Validation Failure - laravel-raw

### ISSUE THREAD

**Issue by msmith-techempower** [TechEmpower/FrameworkBenchmarks#702]
https://github.com/TechEmpower/TFB-Round-9/blob/master/i7/verify-test-1/latest/logs/laravel-raw/out.txt

<b>DB</b>
Invalid response:
expecting `{"id":5892,"randomNumber":4132}`
saw `[{"id":5892,"randomnumber":4132}]`

<b>QUERY</b>
Invalid response: 
expecting `[{"id":7051,"randomNumber":8975},{"id":4258,"randomNumber":3110}]`
saw `[{"id":7051,"randomnumber":8975},{"id":4258,"randomnumber":3110}]`

**Comment by LadyMozzarella** [comment]
Can we close this issue, or demote it from 'Failure' because there are warnings? 

laravel-raw is [passing on master](https://travis-ci.org/TechEmpower/FrameworkBenchmarks/jobs/52758514) at [commit #f9d9df177b35316e6227957c7a93fdaff36ed8b1](https://github.com/TechEmpower/FrameworkBenchmarks/commit/f9d9df177b35316e6227957c7a93fdaff36ed8b1) on 2015/03/03. 
* DB Response: "[{"id":4196,"randomNumber":1753}]"
* Query Response: "[{"id":8830,"randomNumber":4070},{"id":3187,"randomNumber":1325}]"
