### ISSUE TITLE
set up  scala-steward for scala projects?

### ISSUE THREAD

**Issue by hepin1989** [TechEmpower/FrameworkBenchmarks#7240]
Help keep depenency up to date
https://github.com/scala-steward-org/scala-steward

**Comment by nbrady-techempower** [comment]
I don't want to sign up for this for all scala projects. The problem with something like this is certain maintainers may not want to bump certain libraries for performance reasons. I also don't know how noisy it is, etc. We only allow dependabot because we don't want vulnerable packages represented here as best as possible. I also want maintainers to stay engaged with the projects here, or they'll go stale for other reasons. So I think we'll pass on this for now.
