### ISSUE TITLE
Python: Add CherryPy

### ISSUE THREAD

**Issue by TechEmpower** [TechEmpower/FrameworkBenchmarks#77]
http://www.cherrypy.org/

**Comment by knewmanTE** [comment]
I'm going to take a shot at this.

**Comment by hamiltont** [comment]
@knewmanTE cool! I'm interested in seeing how it does!

**Comment by knewmanTE** [comment]
I added CherryPy with basic plaintext and JSON tests.

I also have DB, Queries, and Updates tests mostly implemented, but have excluded them from this merge request because CherryPy relies on a database interface or ORM like SQLAlchemy, and [this part of the TFB Python documentation](https://github.com/TechEmpower/FrameworkBenchmarks/tree/python-cherrypy/frameworks/Python#before-writing-new-tests) seems to indicate that we should avoid redundancy if possible. 

If it's something we decide we want to add later, I can put them in.

**Comment by LadyMozzarella** [comment]
Closing. PR #1424 merged.
