### ISSUE TITLE
ASP.NET Core platform Json and Plaintext

### ISSUE THREAD

**Issue by n-stefan** [TechEmpower/FrameworkBenchmarks#8545]
Hi @sebastienros 
according to the docs, it is recommended to set the DOTNET_SYSTEM_NET_SOCKETS_INLINE_COMPLETIONS environment variable to '1' to also inline the completions at the runtime layer.
Doing so boosts platform Json by ~30% and platform Plaintext by ~20%, at least locally.
Is it OK to open a pull request for it?

**Comment by sebastienros** [comment]
I am not sure why I didn't keep it when doing the recent upgrade (net8.0 + minimal apis).
I just ran all the Platform benchmarks on our machines (Ubuntu 20.04 still) and the issue is Fortunes:

```
INLINE_COMPLETIONS	0		1
Plaintext Platform	11,435,000	11,713,000 # this is limited to 7M on TechEmpower due to network
Json Platform		1,270,000	1,417,000
Fortunes Platform 	470,395  	400,248
Updates Platform	25,612		25,776
Single Queries Platform 499,526		515,577
Multiple Queries	43,545		43,723
```

The current docker image is common to all scenarios, I believe it will be enforced eventually, so we can't set it for selective scenarios.

I assume we could try and see if the composite score is better. But only for Platform for now as I haven't benchmarked it on the other ones and they are more idiomatic.

**Comment by n-stefan** [comment]
OK, pull request only for Platform coming up.

**Comment by n-stefan** [comment]
Hi @sebastienros
looks like inlining completions isn't worth it, the composite score went from 5,854:

https://www.techempower.com/benchmarks/#section=test&runid=341a0547-80f0-45f8-9245-04ae0e0e1bcf&hw=ph&test=composite

to 5,760:

https://www.techempower.com/benchmarks/#section=test&runid=da8306a2-d1d8-4bd3-95d4-59d8cd7047af&hw=ph&test=composite

I would revert the pull request.
