### ISSUE TITLE
Add GraalVM native build for Quarkus

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [TechEmpower/FrameworkBenchmarks#8834]
From a brief look it seems that the Quarkus benchmarks run in JVM mode. I'd love to see the numbers for the native compiled version.

@franz1981, @Sanne: What's your opinion on this? Do you see any blockers? Would you mind if I try a PR with an additional flavor?

**Comment by redkale** [comment]
redkale has  the native compiled version.  see [redkale-native](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/redkale/redkale-native.dockerfile)

**Comment by Sanne** [comment]
Hi hello :)

I love GraalVM native-images, find them really compelling for a lot of use cases - but I believe there are some problems in applying this here.

During our other benchmarking efforts, we identified that native images are very compelling, and sometimes superior, to JVM based solutions when the benchmark focuses on "performance per cost".
This is a very good metric as literally *everyone* should care for such metrics - but currently Techempower doesn't: it's really just a fun competition about pure, raw, maximum unbounded performance - it doesn't matter if you're going to consume 100X more memory but if you get a 1% extra performance, that's a win. The only limitation is to cap yourself at the machines that the Techmpower people have chosen.

In reality it would be very compelling to be able to have approximately the same performance at a fraction of the hardware costs. Even if there were, hypotethically, a small drop in performance, it would still be economically superior to get two instances up if they cost 5% of one big iron.

Considering this, I don't think our solutions based on native-image would give the right impression as people looking at the charts won't really think about such aspects at all... and since we have limited time to maintain various flavours, or make sure they represent the project's potential fairly. So, sadly I think for the time being we'd not want to add such flavours...

Makes sense?

And to be clear, I'd *love* to actually work on this if the benchmark conditions were different... it would be really interesting to have a competition for much lower resource usage. Really cool to see that @redkale is doing it, would be fun to compete indeed :) but I have limited time and can't justify this "fun time" w/o any hopes for it to have any marketing value.

**Comment by Kaliumhexacyanoferrat** [comment]
First of all, thank you for the detailed answer.

I agree about the focus and significance of the benchmarks, although you can also determine and compare interesting metrics regarding memory consumption or average response time from [the details](https://ajdust.github.io/tfbvis/?testrun=Citrine_started2023-09-19_de12400a-863e-4f9e-9b93-dea9eb260422&testtype=fortune&round=false). Nevertheless, benchmarks that focus on efficiency and energy consumption would be a valuable addition.

As soon as the redcale tests run again, I'll take a look at the results there. If there are big differences to be seen here, I might try another PR with GraalVM flavor for Quarkus.
